<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM2W8hya\Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM2W8hya/Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer.php') {
    touch(__DIR__.'/ContainerM2W8hya.legacy');

    return;
}

if (!\class_exists(Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer::class, false)) {
    \class_alias(\ContainerM2W8hya\Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer::class, Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer::class, false);
}

return new \ContainerM2W8hya\Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer([
    'container.build_hash' => 'M2W8hya',
    'container.build_id' => 'bef0bf50',
    'container.build_time' => 1733322258,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM2W8hya');
