<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UH_GGKGService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UH.gGKG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UH.gGKG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'bug_buster_visitors.logger' => ['services', 'BugBuster\\VisitorsBundle\\Classes\\VisitorLogger', 'getVisitorLoggerService', true],
            'contao.cache.entity_tags' => ['services', 'contao.cache.entity_tags', 'getContao_Cache_EntityTagsService', true],
            'contao.csrf.token_manager' => ['services', 'contao.csrf.token_manager', 'getContao_Csrf_TokenManagerService', false],
            'contao.framework' => ['services', 'contao.framework', 'getContao_FrameworkService', false],
            'contao.routing.content_url_generator' => ['services', 'contao.routing.content_url_generator', 'getContao_Routing_ContentUrlGeneratorService', false],
            'contao.routing.scope_matcher' => ['services', 'contao.routing.scope_matcher', 'getContao_Routing_ScopeMatcherService', false],
            'contao.twig.filesystem_loader' => ['services', 'contao.twig.filesystem_loader', 'getContao_Twig_FilesystemLoaderService', false],
            'contao.twig.interop.context_factory' => ['services', 'contao.twig.interop.context_factory', 'getContao_Twig_Interop_ContextFactoryService', true],
            'database_connection' => ['services', 'doctrine.dbal.default_connection', 'getDoctrine_Dbal_DefaultConnectionService', false],
            'event_dispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
            'form.factory' => ['privates', 'form.factory', 'getForm_FactoryService', true],
            'fos_http_cache.http.symfony_response_tagger' => ['services', 'fos_http_cache.http.symfony_response_tagger', 'getFosHttpCache_Http_SymfonyResponseTaggerService', false],
            'http_kernel' => ['services', 'http_kernel', 'getHttpKernelService', false],
            'logger' => ['privates', 'monolog.logger', 'getMonolog_LoggerService', false],
            'parameter_bag' => ['privates', 'parameter_bag', 'getParameterBagService', false],
            'request_stack' => ['services', 'request_stack', 'getRequestStackService', false],
            'router' => ['services', 'router', 'getRouterService', false],
            'security.authorization_checker' => ['services', 'security.authorization_checker', 'getSecurity_AuthorizationCheckerService', false],
            'security.csrf.token_manager' => ['privates', 'security.csrf.token_manager', 'getSecurity_Csrf_TokenManagerService', true],
            'security.helper' => ['services', 'security.helper', 'getSecurity_HelperService', false],
            'security.token_storage' => ['services', 'security.token_storage', 'getSecurity_TokenStorageService', false],
            'translator' => ['services', 'translator', 'getTranslatorService', false],
            'twig' => ['services', 'twig', 'getTwigService', false],
        ], [
            'bug_buster_visitors.logger' => 'BugBuster\\VisitorsBundle\\Classes\\VisitorLogger',
            'contao.cache.entity_tags' => '?',
            'contao.csrf.token_manager' => '?',
            'contao.framework' => '?',
            'contao.routing.content_url_generator' => '?',
            'contao.routing.scope_matcher' => '?',
            'contao.twig.filesystem_loader' => '?',
            'contao.twig.interop.context_factory' => '?',
            'database_connection' => '?',
            'event_dispatcher' => '?',
            'form.factory' => '?',
            'fos_http_cache.http.symfony_response_tagger' => '?',
            'http_kernel' => '?',
            'logger' => '?',
            'parameter_bag' => '?',
            'request_stack' => '?',
            'router' => '?',
            'security.authorization_checker' => '?',
            'security.csrf.token_manager' => '?',
            'security.helper' => '?',
            'security.token_storage' => '?',
            'translator' => '?',
            'twig' => '?',
        ]);
    }
}
