<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VNjN4zFService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vNjN4zF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vNjN4zF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'objAlbum' => ['privates', '.errored..service_locator.vNjN4zF.Markocupic\\GalleryCreatorBundle\\Model\\GalleryCreatorAlbumsModel', NULL, 'Cannot autowire service ".service_locator.vNjN4zF": it needs an instance of "Markocupic\\GalleryCreatorBundle\\Model\\GalleryCreatorAlbumsModel" but this type has been excluded in "config/services.yaml".'],
        ], [
            'objAlbum' => 'Markocupic\\GalleryCreatorBundle\\Model\\GalleryCreatorAlbumsModel',
        ]);
    }
}
