<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAltchaControllerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Markocupic\ContaoAltchaAntispam\Controller\AltchaController' shared autowired service.
     *
     * @return \Markocupic\ContaoAltchaAntispam\Controller\AltchaController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/contao-altcha-antispam/src/Controller/AltchaController.php';

        return $container->services['Markocupic\\ContaoAltchaAntispam\\Controller\\AltchaController'] = new \Markocupic\ContaoAltchaAntispam\Controller\AltchaController(($container->privates['Markocupic\\ContaoAltchaAntispam\\Altcha'] ?? $container->load('getAltchaService')));
    }
}
