<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdvancedClasses_Listener_ParseTemplateService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'advanced_classes.listener.parse_template' shared service.
     *
     * @return \ContaoDD\AdvancedClassesBundle\EventListener\ParseTemplateListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao-dd/advanced-classes-bundle/src/EventListener/ParseTemplateListener.php';

        return $container->services['advanced_classes.listener.parse_template'] = new \ContaoDD\AdvancedClassesBundle\EventListener\ParseTemplateListener();
    }
}
