<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddPasswordListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Markocupic\ImportFromCsvBundle\EventListener\PostImport\AddPasswordListener' shared autowired service.
     *
     * @return \Markocupic\ImportFromCsvBundle\EventListener\PostImport\AddPasswordListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/import-from-csv-bundle/src/EventListener/PostImport/AddPasswordListener.php';

        $a = ($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container));

        if (isset($container->services['Markocupic\\ImportFromCsvBundle\\EventListener\\PostImport\\AddPasswordListener'])) {
            return $container->services['Markocupic\\ImportFromCsvBundle\\EventListener\\PostImport\\AddPasswordListener'];
        }

        return $container->services['Markocupic\\ImportFromCsvBundle\\EventListener\\PostImport\\AddPasswordListener'] = new \Markocupic\ImportFromCsvBundle\EventListener\PostImport\AddPasswordListener($a, ($container->services['security.password_hasher_factory'] ?? $container->load('getSecurity_PasswordHasherFactoryService')));
    }
}
