<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAlbumVoter2Service extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the private '.debug.security.voter.Markocupic\GalleryCreatorBundle\Security\Voter\AlbumVoter' shared service.
     *
     * @return \Symfony\Component\Security\Core\Authorization\Voter\TraceableVoter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/Authorization/Voter/TraceableVoter.php';

        $a = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['.debug.security.voter.Markocupic\\GalleryCreatorBundle\\Security\\Voter\\AlbumVoter'])) {
            return $container->privates['.debug.security.voter.Markocupic\\GalleryCreatorBundle\\Security\\Voter\\AlbumVoter'];
        }

        return $container->privates['.debug.security.voter.Markocupic\\GalleryCreatorBundle\\Security\\Voter\\AlbumVoter'] = new \Symfony\Component\Security\Core\Authorization\Voter\TraceableVoter(($container->services['Markocupic\\GalleryCreatorBundle\\Security\\Voter\\AlbumVoter'] ?? $container->load('getAlbumVoterService')), $a);
    }
}
