<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBackendMenuListener2Service extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the private 'Terminal42\NotificationCenterBundle\EventListener\Backend\BackendMenuListener' shared service.
     *
     * @return \Terminal42\NotificationCenterBundle\EventListener\Backend\BackendMenuListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/notification_center/src/EventListener/Backend/BackendMenuListener.php';

        return $container->privates['Terminal42\\NotificationCenterBundle\\EventListener\\Backend\\BackendMenuListener'] = new \Terminal42\NotificationCenterBundle\EventListener\Backend\BackendMenuListener(($container->services['assets.packages'] ?? self::getAssets_PackagesService($container)));
    }
}
