<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBugbuster_Dlstats_InsertTagsListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'bugbuster.dlstats.insert_tags_listener' shared autowired service.
     *
     * @return \BugBuster\DlstatsBundle\EventListener\ReplaceInsertTagsListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/bugbuster/contao-dlstats-bundle/src/EventListener/ReplaceInsertTagsListener.php';

        return $container->services['bugbuster.dlstats.insert_tags_listener'] = new \BugBuster\DlstatsBundle\EventListener\ReplaceInsertTagsListener(($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)), ($container->services['kernel'] ?? $container->get('kernel', 1)));
    }
}
