<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBugbuster_Dlstatsexport_Listener_PanelService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'bugbuster.dlstatsexport.listener.panel' shared service.
     *
     * @return \BugBuster\DlstatsExportBundle\EventListener\ExportPanelListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/bugbuster/contao-dlstats-statistic-export-bundle/src/EventListener/ExportPanelListener.php';

        return $container->services['bugbuster.dlstatsexport.listener.panel'] = new \BugBuster\DlstatsExportBundle\EventListener\ExportPanelListener(($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)), $container, ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->privates['form.factory'] ?? $container->load('getForm_FactoryService')));
    }
}
