<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBugbuster_Dlstatsexport_Form_Type_RequestTokenService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the private 'bugbuster.dlstatsexport.form.type.request_token' shared autowired service.
     *
     * @return \BugBuster\DlstatsExportBundle\Form\Type\RequestTokenType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/Extension/Core/Type/HiddenType.php';
        include_once \dirname(__DIR__, 4).'/vendor/bugbuster/contao-dlstats-statistic-export-bundle/src/Form/Type/RequestTokenType.php';

        return $container->privates['bugbuster.dlstatsexport.form.type.request_token'] = new \BugBuster\DlstatsExportBundle\Form\Type\RequestTokenType(($container->services['contao.csrf.token_manager'] ?? self::getContao_Csrf_TokenManagerService($container)), 'contao_csrf_token');
    }
}
