<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBackendAccessVoter2Service extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the private 'Codefog\NewsCategoriesBundle\Security\Voter\BackendAccessVoter' shared autowired service.
     *
     * @return \Codefog\NewsCategoriesBundle\Security\Voter\BackendAccessVoter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/codefog/contao-news_categories/src/Security/Voter/BackendAccessVoter.php';

        return $container->privates['Codefog\\NewsCategoriesBundle\\Security\\Voter\\BackendAccessVoter'] = new \Codefog\NewsCategoriesBundle\Security\Voter\BackendAccessVoter(($container->services['contao.framework'] ?? self::getContao_FrameworkService($container)));
    }
}
