<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBackendAccessVoterService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the private '.debug.security.voter.Codefog\NewsCategoriesBundle\Security\Voter\BackendAccessVoter' shared service.
     *
     * @return \Symfony\Component\Security\Core\Authorization\Voter\TraceableVoter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/Authorization/Voter/TraceableVoter.php';

        $a = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['.debug.security.voter.Codefog\\NewsCategoriesBundle\\Security\\Voter\\BackendAccessVoter'])) {
            return $container->privates['.debug.security.voter.Codefog\\NewsCategoriesBundle\\Security\\Voter\\BackendAccessVoter'];
        }

        return $container->privates['.debug.security.voter.Codefog\\NewsCategoriesBundle\\Security\\Voter\\BackendAccessVoter'] = new \Symfony\Component\Security\Core\Authorization\Voter\TraceableVoter(($container->privates['Codefog\\NewsCategoriesBundle\\Security\\Voter\\BackendAccessVoter'] ?? $container->load('getBackendAccessVoter2Service')), $a);
    }
}
