<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCtn_Themecomponentsbundle_Eventlistener_ParsefrontendtemplatehookService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'ctn.themecomponentsbundle.eventlistener.parsefrontendtemplatehook' shared autowired service.
     *
     * @return \ContaoThemesNet\ThemeComponentsBundle\EventListener\ParseFrontendTemplateHook
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao-themes-net/theme-components-bundle/src/EventListener/ParseFrontendTemplateHook.php';

        return $container->services['ctn.themecomponentsbundle.eventlistener.parsefrontendtemplatehook'] = new \ContaoThemesNet\ThemeComponentsBundle\EventListener\ParseFrontendTemplateHook();
    }
}
