<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConfigOnLoadCallbackListener2Service extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'InspiredMinds\ContaoEventRegistration\EventListener\DataContainer\EventRegistration\ConfigOnLoadCallbackListener' shared autowired service.
     *
     * @return \InspiredMinds\ContaoEventRegistration\EventListener\DataContainer\EventRegistration\ConfigOnLoadCallbackListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/inspiredminds/contao-event-registration/src/EventListener/DataContainer/EventRegistration/ConfigOnLoadCallbackListener.php';

        return $container->services['InspiredMinds\\ContaoEventRegistration\\EventListener\\DataContainer\\EventRegistration\\ConfigOnLoadCallbackListener'] = new \InspiredMinds\ContaoEventRegistration\EventListener\DataContainer\EventRegistration\ConfigOnLoadCallbackListener();
    }
}
