<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContao_Fragment_Contao_FrontendModule_CheckListingService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'contao.fragment._contao.frontend_module.check_listing' shared autowired service.
     *
     * @return \Diversworld\ContaoCheckBundle\Controller\FrontendModule\CheckListingController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Fragment/FragmentOptionsAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Controller/AbstractFragmentController.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Controller/FrontendModule/AbstractFrontendModuleController.php';
        include_once \dirname(__DIR__, 4).'/vendor/diversworld/contao-check-bundle/src/Controller/FrontendModule/CheckListingController.php';

        $container->services['contao.fragment._contao.frontend_module.check_listing'] = $instance = new \Diversworld\ContaoCheckBundle\Controller\FrontendModule\CheckListingController();

        $instance->setFragmentOptions(['type' => 'check_listing', 'category' => 'check_modules', 'template' => 'mod_check_listing', 'method' => NULL, 'renderer' => NULL, 'priority' => 0, 'debugController' => 'Diversworld\\ContaoCheckBundle\\Controller\\FrontendModule\\CheckListingController']);
        $instance->setContainer(($container->privates['.service_locator.3wBV1id'] ?? $container->load('get_ServiceLocator_3wBV1idService'))->withContext('contao.fragment._contao.frontend_module.check_listing', $container));

        return $instance;
    }
}
