<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCtn_Materialiconsinserttag_Listener_HooksService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'ctn.materialiconsinserttag.listener.hooks' shared service.
     *
     * @return \ContaoThemesNet\MaterialIconsInserttag\EventListener\HookListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao-themes-net/material-icons-inserttag/src/EventListener/HookListener.php';

        return $container->services['ctn.materialiconsinserttag.listener.hooks'] = new \ContaoThemesNet\MaterialIconsInserttag\EventListener\HookListener(($container->services['contao.framework'] ?? self::getContao_FrameworkService($container)));
    }
}
