<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCookieConfigCallbackListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Oveleon\ContaoCookiebar\EventListener\DataContainer\CookieConfigCallbackListener' shared autowired service.
     *
     * @return \Oveleon\ContaoCookiebar\EventListener\DataContainer\CookieConfigCallbackListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/oveleon/contao-cookiebar/src/EventListener/DataContainer/CookiebarTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/oveleon/contao-cookiebar/src/EventListener/DataContainer/CookieConfigCallbackListener.php';

        return $container->services['Oveleon\\ContaoCookiebar\\EventListener\\DataContainer\\CookieConfigCallbackListener'] = new \Oveleon\ContaoCookiebar\EventListener\DataContainer\CookieConfigCallbackListener();
    }
}
