<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCookieCallbackListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Oveleon\ContaoCookiebar\EventListener\DataContainer\CookieCallbackListener' shared autowired service.
     *
     * @return \Oveleon\ContaoCookiebar\EventListener\DataContainer\CookieCallbackListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/oveleon/contao-cookiebar/src/EventListener/DataContainer/CookiebarTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/oveleon/contao-cookiebar/src/EventListener/DataContainer/CookieCallbackListener.php';

        return $container->services['Oveleon\\ContaoCookiebar\\EventListener\\DataContainer\\CookieCallbackListener'] = new \Oveleon\ContaoCookiebar\EventListener\DataContainer\CookieCallbackListener(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)), ($container->services['translator'] ?? self::getTranslatorService($container)));
    }
}
