<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContao_Listener_0wFBrYrService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'contao.listener.0wFBrYr' shared service.
     *
     * @return \Contao\CoreBundle\EventListener\GlobalsMapListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/EventListener/GlobalsMapListener.php';

        return $container->services['contao.listener.0wFBrYr'] = new \Contao\CoreBundle\EventListener\GlobalsMapListener(['FE_MOD' => ['miscellaneous' => ['visitors' => 'Contao\\ModuleProxy', 'feed_reader' => 'Contao\\ModuleProxy', 'root_page_dependent_modules' => 'Contao\\ModuleProxy', 'template' => 'Contao\\ModuleProxy', 'unfiltered_html' => 'Contao\\ModuleProxy', 'image_copyright_list' => 'Contao\\ModuleProxy', 'pageimage' => 'Contao\\ModuleProxy'], 'user' => ['two_factor' => 'Contao\\ModuleProxy', 'lostPasswordNotificationCenter' => 'Contao\\ModuleProxy', 'registrationNotificationCenter' => 'Contao\\ModuleProxy'], 'application' => ['cookiebar_opener' => 'Contao\\ModuleProxy'], 'check_modules' => ['check_listing' => 'Contao\\ModuleProxy'], 'newsletter' => ['newsletterSubscribeNotificationCenter' => 'Contao\\ModuleProxy', 'newsletterUnsubscribeNotificationCenter' => 'Contao\\ModuleProxy'], 'leads' => ['leadsoptin' => 'Contao\\ModuleProxy'], 'events' => ['event_registration_cancel' => 'Contao\\ModuleProxy', 'event_registration_confirm' => 'Contao\\ModuleProxy', 'event_registration_form' => 'Contao\\ModuleProxy', 'event_registration_list' => 'Contao\\ModuleProxy']]]);
    }
}
