<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContao_Fragment_Contao_FrontendModule_NewsletterUnsubscribeNotificationCenterService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'contao.fragment._contao.frontend_module.newsletterUnsubscribeNotificationCenter' shared service.
     *
     * @return \Terminal42\NotificationCenterBundle\Controller\FrontendModule\Newsletter\UnsubscribeController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/contao/classes/Frontend.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/contao/modules/Module.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/newsletter-bundle/contao/modules/ModuleUnsubscribe.php';
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/notification_center/src/Controller/FrontendModule/Newsletter/UnsubscribeController.php';

        return $container->services['contao.fragment._contao.frontend_module.newsletterUnsubscribeNotificationCenter'] = new \Terminal42\NotificationCenterBundle\Controller\FrontendModule\Newsletter\UnsubscribeController(($container->privates['Terminal42\\NotificationCenterBundle\\NotificationCenter'] ?? $container->load('getNotificationCenterService')));
    }
}
