<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCode4nixUriSigner_UriSignerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'code4nix_uri_signer.uri_signer' shared service.
     *
     * @return \Code4Nix\UriSigner\UriSigner
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/code4nix/uri-signer/src/UriSigner.php';

        return $container->services['code4nix_uri_signer.uri_signer'] = new \Code4Nix\UriSigner\UriSigner($container->getEnv('APP_SECRET'), '_hash', 3600);
    }
}
