<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContaoPdfformsbundle_Listener_PrepareFormDataService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'contao_pdfformsbundle.listener.prepare_form_data' shared autowired service.
     *
     * @return \Softleister\PdfformsBundle\EventListener\PrepareFormDataListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/do-while/contao-pdfforms-bundle/src/EventListener/PrepareFormDataListener.php';

        return $container->services['contao_pdfformsbundle.listener.prepare_form_data'] = new \Softleister\PdfformsBundle\EventListener\PrepareFormDataListener(($container->services['contao.framework'] ?? self::getContao_FrameworkService($container)));
    }
}
