<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChmodTableService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Markocupic\GalleryCreatorBundle\Widget\Backend\ChmodTable' shared autowired service.
     *
     * @return \Markocupic\GalleryCreatorBundle\Widget\Backend\ChmodTable
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/contao/library/Contao/TemplateInheritance.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/contao/library/Contao/TemplateTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/contao/library/Contao/Widget.php';
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/gallery-creator-bundle/src/Widget/Backend/ChmodTable.php';

        return $container->services['Markocupic\\GalleryCreatorBundle\\Widget\\Backend\\ChmodTable'] = new \Markocupic\GalleryCreatorBundle\Widget\Backend\ChmodTable();
    }
}
