<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCookiebar_AnonymizeipService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the private 'cookiebar.anonymizeip' shared service.
     *
     * @return \Oveleon\ContaoCookiebar\Command\AnonymizeIpCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/oveleon/contao-cookiebar/src/Command/AnonymizeIpCommand.php';

        $container->privates['cookiebar.anonymizeip'] = $instance = new \Oveleon\ContaoCookiebar\Command\AnonymizeIpCommand(($container->services['contao.framework'] ?? self::getContao_FrameworkService($container)));

        $instance->setName('cookiebar:anonymizeip');
        $instance->setDescription('Anonymizes all IP addresses in the log');

        return $instance;
    }
}
