<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCalendarEventsListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Pdir\MaeEventCategoriesBundle\EventListener\DataContainer\CalendarEventsListener' shared autowired service.
     *
     * @return \Pdir\MaeEventCategoriesBundle\EventListener\DataContainer\CalendarEventsListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/marebe1602/mae_event_categories/src/EventListener/DataContainer/CalendarEventsListener.php';

        return $container->services['Pdir\\MaeEventCategoriesBundle\\EventListener\\DataContainer\\CalendarEventsListener'] = new \Pdir\MaeEventCategoriesBundle\EventListener\DataContainer\CalendarEventsListener(($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)));
    }
}
