<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCheckAuthServiceService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'DanielGausi\CalendarEditorBundle\Services\CheckAuthService' shared autowired service.
     *
     * @return \DanielGausi\CalendarEditorBundle\Services\CheckAuthService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/danielgausi/contao-calendareditor-bundle/src/Services/CheckAuthService.php';

        return $container->services['DanielGausi\\CalendarEditorBundle\\Services\\CheckAuthService'] = new \DanielGausi\CalendarEditorBundle\Services\CheckAuthService(($container->services['security.helper'] ?? self::getSecurity_HelperService($container)));
    }
}
