<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getColorPickerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the private 'MenAtWork\MultiColumnWizardBundle\EventListener\Mcw\ColorPicker' shared service.
     *
     * @return \MenAtWork\MultiColumnWizardBundle\EventListener\Mcw\ColorPicker
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/menatwork/contao-multicolumnwizard-bundle/src/EventListener/Mcw/ColorPicker.php';

        return $container->privates['MenAtWork\\MultiColumnWizardBundle\\EventListener\\Mcw\\ColorPicker'] = new \MenAtWork\MultiColumnWizardBundle\EventListener\Mcw\ColorPicker(($container->services['contao.framework'] ?? self::getContao_FrameworkService($container))->getAdapter("Contao\\Image"), ($container->services['contao.framework'] ?? self::getContao_FrameworkService($container))->getAdapter("Contao\\StringUtil"), ($container->services['translator'] ?? self::getTranslatorService($container)));
    }
}
