<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCalendarExtended_Mcw_CallbacksService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'calendar_extended.mcw.callbacks' shared autowired service.
     *
     * @return \Cgoit\CalendarExtendedBundle\EventListener\DataContainer\CalendarEventsMCWCallbacks
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/contao/classes/Backend.php';
        include_once \dirname(__DIR__, 4).'/vendor/cgoit/calendar-extended-bundle/src/EventListener/DataContainer/CalendarEventsMCWCallbacks.php';

        return $container->services['calendar_extended.mcw.callbacks'] = new \Cgoit\CalendarExtendedBundle\EventListener\DataContainer\CalendarEventsMCWCallbacks(($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)), 7, $container->parameters['cgoit_calendar_extended.exceptions.move_times']);
    }
}
