<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConditionFieldOptionsListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Terminal42\ConditionalSelectMenuBundle\EventListener\ConditionFieldOptionsListener' shared autowired service.
     *
     * @return \Terminal42\ConditionalSelectMenuBundle\EventListener\ConditionFieldOptionsListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-conditionalselectmenu/src/EventListener/ConditionFieldOptionsListener.php';

        return $container->services['Terminal42\\ConditionalSelectMenuBundle\\EventListener\\ConditionFieldOptionsListener'] = new \Terminal42\ConditionalSelectMenuBundle\EventListener\ConditionFieldOptionsListener(($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)));
    }
}
