<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConfigOnShowCallbackListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'InspiredMinds\ContaoEventRegistration\EventListener\DataContainer\EventRegistration\ConfigOnShowCallbackListener' shared autowired service.
     *
     * @return \InspiredMinds\ContaoEventRegistration\EventListener\DataContainer\EventRegistration\ConfigOnShowCallbackListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/inspiredminds/contao-event-registration/src/EventListener/DataContainer/EventRegistration/ConfigOnShowCallbackListener.php';

        return $container->services['InspiredMinds\\ContaoEventRegistration\\EventListener\\DataContainer\\EventRegistration\\ConfigOnShowCallbackListener'] = new \InspiredMinds\ContaoEventRegistration\EventListener\DataContainer\EventRegistration\ConfigOnShowCallbackListener();
    }
}
