<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContao_Fragment_Contao_FrontendModule_PageimageService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'contao.fragment._contao.frontend_module.pageimage' shared service.
     *
     * @return \Terminal42\PageimageBundle\Controller\PageimageController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Fragment/FragmentOptionsAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Controller/AbstractFragmentController.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Controller/FrontendModule/AbstractFrontendModuleController.php';
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-pageimage/src/Controller/PageimageController.php';
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-pageimage/src/PageimageHelper.php';

        $container->services['contao.fragment._contao.frontend_module.pageimage'] = $instance = new \Terminal42\PageimageBundle\Controller\PageimageController(($container->privates['Terminal42\\PageimageBundle\\PageimageHelper'] ??= new \Terminal42\PageimageBundle\PageimageHelper()), ($container->services['contao.image.studio'] ?? $container->load('getContao_Image_StudioService')));

        $a = $container->load('get_ServiceLocator_NqgdEu8_Contao_Fragment_Contao_FrontendModule_PageimageService');

        $instance->setContainer($a);
        $instance->setFragmentOptions(['type' => 'pageimage', 'category' => 'miscellaneous', 'template' => 'mod_pageimage', 'method' => NULL, 'renderer' => NULL, 'priority' => 0, 'debugController' => 'Terminal42\\PageimageBundle\\Controller\\PageimageController']);
        $instance->setContainer($a);

        return $instance;
    }
}
