<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCodefogTags_Listener_InsertTagsService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'codefog_tags.listener.insert_tags' shared service.
     *
     * @return \Codefog\TagsBundle\EventListener\InsertTagsListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/codefog/tags-bundle/src/EventListener/InsertTagsListener.php';

        return $container->services['codefog_tags.listener.insert_tags'] = new \Codefog\TagsBundle\EventListener\InsertTagsListener(($container->services['codefog_tags.manager_registry'] ?? $container->load('getCodefogTags_ManagerRegistryService')));
    }
}
