<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContao_Fragment_Contao_FrontendModule_VisitorsService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'contao.fragment._contao.frontend_module.visitors' shared autowired service.
     *
     * @return \BugBuster\VisitorsBundle\Controller\FrontendModule\VisitorsFrontendController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Fragment/FragmentOptionsAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Controller/AbstractFragmentController.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Controller/FrontendModule/AbstractFrontendModuleController.php';
        include_once \dirname(__DIR__, 4).'/vendor/bugbuster/contao-visitors-bundle/src/Controller/FrontendModule/VisitorsFrontendController.php';

        $container->services['contao.fragment._contao.frontend_module.visitors'] = $instance = new \BugBuster\VisitorsBundle\Controller\FrontendModule\VisitorsFrontendController();

        $instance->setFragmentOptions(['category' => 'miscellaneous', 'type' => 'visitors', 'template' => 'mod_visitors_fe_all', 'renderer' => 'esi', 'debugController' => 'BugBuster\\VisitorsBundle\\Controller\\FrontendModule\\VisitorsFrontendController']);
        $instance->setContainer(($container->privates['.service_locator.UH.gGKG'] ?? $container->load('get_ServiceLocator_UH_GGKGService'))->withContext('contao.fragment._contao.frontend_module.visitors', $container));

        return $instance;
    }
}
