<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCalendarEventsCallbacksService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Cgoit\CalendarExtendedBundle\EventListener\DataContainer\CalendarEventsCallbacks' shared autowired service.
     *
     * @return \Cgoit\CalendarExtendedBundle\EventListener\DataContainer\CalendarEventsCallbacks
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/contao/classes/Backend.php';
        include_once \dirname(__DIR__, 4).'/vendor/cgoit/calendar-extended-bundle/src/EventListener/DataContainer/CalendarEventsCallbacks.php';

        return $container->services['Cgoit\\CalendarExtendedBundle\\EventListener\\DataContainer\\CalendarEventsCallbacks'] = new \Cgoit\CalendarExtendedBundle\EventListener\DataContainer\CalendarEventsCallbacks(($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), 365, 250);
    }
}
