<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDwCheckService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Diversworld\ContaoCheckBundle\DataContainer\DwCheck' shared autowired service.
     *
     * @return \Diversworld\ContaoCheckBundle\DataContainer\DwCheck
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/diversworld/contao-check-bundle/src/DataContainer/DwCheck.php';

        return $container->services['Diversworld\\ContaoCheckBundle\\DataContainer\\DwCheck'] = new \Diversworld\ContaoCheckBundle\DataContainer\DwCheck(($container->services['contao.framework'] ?? self::getContao_FrameworkService($container)));
    }
}
