<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDateAddedFieldListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'HeimrichHannot\UtilsBundle\EventListener\DcaField\DateAddedFieldListener' shared autowired service.
     *
     * @return \HeimrichHannot\UtilsBundle\EventListener\DcaField\DateAddedFieldListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/heimrichhannot/contao-utils-bundle/src/EventListener/DcaField/AbstractDcaFieldListener.php';
        include_once \dirname(__DIR__, 4).'/vendor/heimrichhannot/contao-utils-bundle/src/EventListener/DcaField/DateAddedFieldListener.php';

        return $container->services['HeimrichHannot\\UtilsBundle\\EventListener\\DcaField\\DateAddedFieldListener'] = new \HeimrichHannot\UtilsBundle\EventListener\DcaField\DateAddedFieldListener((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'contao.framework' => ['services', 'contao.framework', 'getContao_FrameworkService', false],
        ], [
            'contao.framework' => '?',
        ]))->withContext('HeimrichHannot\\UtilsBundle\\EventListener\\DcaField\\DateAddedFieldListener', $container));
    }
}
