<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDcaFilesListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Tastaturberuf\ContaoImageCopyrightBundle\EventListener\DcaFilesListener' shared autowired service.
     *
     * @return \Tastaturberuf\ContaoImageCopyrightBundle\EventListener\DcaFilesListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/tastaturberuf/contao-image-copyright-bundle/EventListener/DcaFilesListener.php';

        return $container->services['Tastaturberuf\\ContaoImageCopyrightBundle\\EventListener\\DcaFilesListener'] = new \Tastaturberuf\ContaoImageCopyrightBundle\EventListener\DcaFilesListener($container->parameters['contao.image.valid_extensions']);
    }
}
