<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExportTypeOptionsListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Terminal42\LeadsBundle\EventListener\DataContainer\ExportTypeOptionsListener' shared autowired service.
     *
     * @return \Terminal42\LeadsBundle\EventListener\DataContainer\ExportTypeOptionsListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-leads/src/EventListener/DataContainer/ExportTypeOptionsListener.php';

        return $container->services['Terminal42\\LeadsBundle\\EventListener\\DataContainer\\ExportTypeOptionsListener'] = new \Terminal42\LeadsBundle\EventListener\DataContainer\ExportTypeOptionsListener(($container->privates['terminal42_leads.exporters'] ?? $container->load('getTerminal42Leads_ExportersService')), ($container->services['translator'] ?? self::getTranslatorService($container)));
    }
}
