<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventRegistrationService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the private 'InspiredMinds\ContaoEventRegistration\EventRegistration' shared autowired service.
     *
     * @return \InspiredMinds\ContaoEventRegistration\EventRegistration
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/inspiredminds/contao-event-registration/src/EventRegistration.php';

        $a = ($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container));

        if (isset($container->privates['InspiredMinds\\ContaoEventRegistration\\EventRegistration'])) {
            return $container->privates['InspiredMinds\\ContaoEventRegistration\\EventRegistration'];
        }

        return $container->privates['InspiredMinds\\ContaoEventRegistration\\EventRegistration'] = new \InspiredMinds\ContaoEventRegistration\EventRegistration($a, $container->parameters['kernel.bundles']);
    }
}
