<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExportControllerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'BugBuster\DlstatsExportBundle\Controller\ExportController' shared autowired service.
     *
     * @return \BugBuster\DlstatsExportBundle\Controller\ExportController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/bugbuster/contao-dlstats-statistic-export-bundle/src/Controller/ExportController.php';

        $container->services['BugBuster\\DlstatsExportBundle\\Controller\\ExportController'] = $instance = new \BugBuster\DlstatsExportBundle\Controller\ExportController();

        $instance->setContainer($container);

        return $instance;
    }
}
