<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEntityFinderCommandService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the private 'HeimrichHannot\UtilsBundle\Command\EntityFinderCommand' shared autowired service.
     *
     * @return \HeimrichHannot\UtilsBundle\Command\EntityFinderCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/heimrichhannot/contao-utils-bundle/src/Command/EntityFinderCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/heimrichhannot/contao-utils-bundle/src/EntityFinder/EntityFinderHelper.php';

        $a = ($container->services['contao.framework'] ?? self::getContao_FrameworkService($container));

        $container->privates['HeimrichHannot\\UtilsBundle\\Command\\EntityFinderCommand'] = $instance = new \HeimrichHannot\UtilsBundle\Command\EntityFinderCommand($a, ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container)), ($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)), new \HeimrichHannot\UtilsBundle\EntityFinder\EntityFinderHelper(($container->services['HeimrichHannot\\UtilsBundle\\Util\\Utils'] ?? self::getUtilsService($container)), $a));

        $instance->setName('huh:utils:entity_finder');
        $instance->setDescription('A command to find where an entity is included.');

        return $instance;
    }
}
