<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExportButtonsListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Terminal42\LeadsBundle\EventListener\DataContainer\ExportButtonsListener' shared autowired service.
     *
     * @return \Terminal42\LeadsBundle\EventListener\DataContainer\ExportButtonsListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-leads/src/EventListener/DataContainer/ExportButtonsListener.php';

        return $container->services['Terminal42\\LeadsBundle\\EventListener\\DataContainer\\ExportButtonsListener'] = new \Terminal42\LeadsBundle\EventListener\DataContainer\ExportButtonsListener(($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['security.authorization_checker'] ?? self::getSecurity_AuthorizationCheckerService($container)), ($container->services['translator'] ?? self::getTranslatorService($container)), ($container->privates['terminal42_leads.exporters'] ?? $container->load('getTerminal42Leads_ExportersService')));
    }
}
