<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventRegistrationConfirmControllerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'InspiredMinds\ContaoEventRegistration\Controller\FrontendModule\EventRegistrationConfirmController' shared autowired service.
     *
     * @return \InspiredMinds\ContaoEventRegistration\Controller\FrontendModule\EventRegistrationConfirmController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Fragment/FragmentOptionsAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Controller/AbstractFragmentController.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Controller/FrontendModule/AbstractFrontendModuleController.php';
        include_once \dirname(__DIR__, 4).'/vendor/inspiredminds/contao-event-registration/src/Controller/FrontendModule/EventRegistrationConfirmController.php';
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-node/src/NodeManager.php';

        $container->services['InspiredMinds\\ContaoEventRegistration\\Controller\\FrontendModule\\EventRegistrationConfirmController'] = $instance = new \InspiredMinds\ContaoEventRegistration\Controller\FrontendModule\EventRegistrationConfirmController(($container->privates['InspiredMinds\\ContaoEventRegistration\\EventRegistration'] ?? $container->load('getEventRegistrationService')), ($container->services['terminal42_node.manager'] ??= new \Terminal42\NodeBundle\NodeManager()), ($container->services['translator'] ?? self::getTranslatorService($container)), ($container->services['contao.string.simple_token_parser'] ?? $container->load('getContao_String_SimpleTokenParserService')), ($container->privates['Terminal42\\NotificationCenterBundle\\NotificationCenter'] ?? $container->load('getNotificationCenterService')));

        $instance->setContainer(($container->privates['.service_locator..72JI_b'] ?? $container->load('get_ServiceLocator__72JIBService'))->withContext('InspiredMinds\\ContaoEventRegistration\\Controller\\FrontendModule\\EventRegistrationConfirmController', $container));

        return $instance;
    }
}
