<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormatter2Service extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Markocupic\ImportFromCsvBundle\Import\Field\Formatter' shared autowired service.
     *
     * @return \Markocupic\ImportFromCsvBundle\Import\Field\Formatter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/import-from-csv-bundle/src/Import/Field/Formatter.php';

        return $container->services['Markocupic\\ImportFromCsvBundle\\Import\\Field\\Formatter'] = new \Markocupic\ImportFromCsvBundle\Import\Field\Formatter(($container->services['contao.framework'] ?? self::getContao_FrameworkService($container)));
    }
}
