<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Cgoit\LeadsOptinBundle\EventListener\DataContainer\Form' shared autowired service.
     *
     * @return \Cgoit\LeadsOptinBundle\EventListener\DataContainer\Form
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/cgoit/contao-leads-optin-bundle/src/EventListener/DataContainer/Form.php';

        return $container->services['Cgoit\\LeadsOptinBundle\\EventListener\\DataContainer\\Form'] = new \Cgoit\LeadsOptinBundle\EventListener\DataContainer\Form(($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)));
    }
}
