<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFolderPageControllerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Terminal42\FolderpageBundle\Controller\FolderPageController' shared autowired service.
     *
     * @return \Terminal42\FolderpageBundle\Controller\FolderPageController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-folderpage/src/Controller/FolderPageController.php';

        return $container->services['Terminal42\\FolderpageBundle\\Controller\\FolderPageController'] = new \Terminal42\FolderpageBundle\Controller\FolderPageController();
    }
}
