<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGalleryCreatorNewsControllerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Markocupic\GalleryCreatorBundle\Controller\ContentElement\GalleryCreatorNewsController' shared autowired service.
     *
     * @return \Markocupic\GalleryCreatorBundle\Controller\ContentElement\GalleryCreatorNewsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Fragment/FragmentOptionsAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Controller/AbstractFragmentController.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Controller/ContentElement/AbstractContentElementController.php';
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/gallery-creator-bundle/src/Controller/ContentElement/AbstractGalleryCreatorController.php';
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/gallery-creator-bundle/src/Controller/ContentElement/GalleryCreatorNewsController.php';

        $container->services['Markocupic\\GalleryCreatorBundle\\Controller\\ContentElement\\GalleryCreatorNewsController'] = $instance = new \Markocupic\GalleryCreatorBundle\Controller\ContentElement\GalleryCreatorNewsController(($container->services['Markocupic\\GalleryCreatorBundle\\Controller\\ContentElement\\DependencyAggregate'] ?? $container->load('getDependencyAggregateService')), ($container->services['twig'] ?? self::getTwigService($container)));

        $instance->setContainer(($container->privates['.service_locator.6QgB1j.'] ?? $container->load('get_ServiceLocator_6QgB1j_Service'))->withContext('Markocupic\\GalleryCreatorBundle\\Controller\\ContentElement\\GalleryCreatorNewsController', $container));

        return $instance;
    }
}
