<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGalleryCreatorAlbumPermissionsService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Markocupic\GalleryCreatorBundle\Security\GalleryCreatorAlbumPermissions' shared autowired service.
     *
     * @return \Markocupic\GalleryCreatorBundle\Security\GalleryCreatorAlbumPermissions
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/gallery-creator-bundle/src/Security/GalleryCreatorAlbumPermissions.php';

        return $container->services['Markocupic\\GalleryCreatorBundle\\Security\\GalleryCreatorAlbumPermissions'] = new \Markocupic\GalleryCreatorBundle\Security\GalleryCreatorAlbumPermissions();
    }
}
