<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetAllEventsHookService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Cgoit\CalendarExtendedBundle\Hook\GetAllEventsHook' shared autowired service.
     *
     * @return \Cgoit\CalendarExtendedBundle\Hook\GetAllEventsHook
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/cgoit/calendar-extended-bundle/src/Hook/GetAllEventsHook.php';

        return $container->services['Cgoit\\CalendarExtendedBundle\\Hook\\GetAllEventsHook'] = new \Cgoit\CalendarExtendedBundle\Hook\GetAllEventsHook();
    }
}
