<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGeneratePageListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Pdir\ContaoWebtoolsBundle\EventListener\GeneratePageListener' shared autowired service.
     *
     * @return \Pdir\ContaoWebtoolsBundle\EventListener\GeneratePageListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pdir/contao-webtools/src/EventListener/GeneratePageListener.php';

        return $container->services['Pdir\\ContaoWebtoolsBundle\\EventListener\\GeneratePageListener'] = new \Pdir\ContaoWebtoolsBundle\EventListener\GeneratePageListener();
    }
}
