<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGalleryCreatorAjaxService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Markocupic\GalleryCreatorBundle\Controller\Ajax\GalleryCreatorAjax' shared autowired service.
     *
     * @return \Markocupic\GalleryCreatorBundle\Controller\Ajax\GalleryCreatorAjax
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/gallery-creator-bundle/src/Controller/Ajax/GalleryCreatorAjax.php';

        return $container->services['Markocupic\\GalleryCreatorBundle\\Controller\\Ajax\\GalleryCreatorAjax'] = new \Markocupic\GalleryCreatorBundle\Controller\Ajax\GalleryCreatorAjax(($container->services['contao.framework'] ?? self::getContao_FrameworkService($container)), ($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)), ($container->services['Markocupic\\GalleryCreatorBundle\\Util\\SecurityUtil'] ?? $container->load('getSecurityUtilService')), ($container->services['Markocupic\\GalleryCreatorBundle\\Util\\AlbumUtil'] ?? $container->load('getAlbumUtilService')), ($container->services['Markocupic\\GalleryCreatorBundle\\Util\\PictureUtil'] ?? $container->load('getPictureUtilService')));
    }
}
