<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGalleryCreatorAlbumsModel2Service extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.sKMpniw.Markocupic\GalleryCreatorBundle\Model\GalleryCreatorAlbumsModel' shared service.
     *
     * @return \Markocupic\GalleryCreatorBundle\Model\GalleryCreatorAlbumsModel
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.sKMpniw": it needs an instance of "Markocupic\\GalleryCreatorBundle\\Model\\GalleryCreatorAlbumsModel" but this type has been excluded in "config/services.yaml".');
    }
}
