<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGalleryCreatorControllerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Markocupic\GalleryCreatorBundle\Controller\ContentElement\GalleryCreatorController' shared autowired service.
     *
     * @return \Markocupic\GalleryCreatorBundle\Controller\ContentElement\GalleryCreatorController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Fragment/FragmentOptionsAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Controller/AbstractFragmentController.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Controller/ContentElement/AbstractContentElementController.php';
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/gallery-creator-bundle/src/Controller/ContentElement/AbstractGalleryCreatorController.php';
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/gallery-creator-bundle/src/Controller/ContentElement/GalleryCreatorController.php';

        $container->services['Markocupic\\GalleryCreatorBundle\\Controller\\ContentElement\\GalleryCreatorController'] = $instance = new \Markocupic\GalleryCreatorBundle\Controller\ContentElement\GalleryCreatorController(($container->services['Markocupic\\GalleryCreatorBundle\\Controller\\ContentElement\\DependencyAggregate'] ?? $container->load('getDependencyAggregateService')), ($container->services['contao.framework'] ?? self::getContao_FrameworkService($container)), ($container->services['twig'] ?? self::getTwigService($container)), ($container->services['contao.string.html_decoder'] ?? $container->load('getContao_String_HtmlDecoderService')), ($container->services['fos_http_cache.http.symfony_response_tagger'] ?? self::getFosHttpCache_Http_SymfonyResponseTaggerService($container)));

        $instance->setContainer(($container->privates['.service_locator.6QgB1j.'] ?? $container->load('get_ServiceLocator_6QgB1j_Service'))->withContext('Markocupic\\GalleryCreatorBundle\\Controller\\ContentElement\\GalleryCreatorController', $container));

        return $instance;
    }
}
