<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHuh_Ajax_TokenService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'huh.ajax.token' shared autowired service.
     *
     * @return \HeimrichHannot\AjaxBundle\Manager\AjaxTokenManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/heimrichhannot/contao-ajax-bundle/src/Manager/AjaxTokenManager.php';

        return $container->services['huh.ajax.token'] = new \HeimrichHannot\AjaxBundle\Manager\AjaxTokenManager(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['HeimrichHannot\\UtilsBundle\\Util\\Utils'] ?? self::getUtilsService($container)));
    }
}
