<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHeaderCallbackListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'InspiredMinds\ContaoEventRegistration\EventListener\DataContainer\EventRegistration\HeaderCallbackListener' shared autowired service.
     *
     * @return \InspiredMinds\ContaoEventRegistration\EventListener\DataContainer\EventRegistration\HeaderCallbackListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/inspiredminds/contao-event-registration/src/EventListener/DataContainer/EventRegistration/HeaderCallbackListener.php';

        return $container->services['InspiredMinds\\ContaoEventRegistration\\EventListener\\DataContainer\\EventRegistration\\HeaderCallbackListener'] = new \InspiredMinds\ContaoEventRegistration\EventListener\DataContainer\EventRegistration\HeaderCallbackListener(($container->privates['InspiredMinds\\ContaoEventRegistration\\EventRegistration'] ?? $container->load('getEventRegistrationService')), ($container->services['translator'] ?? self::getTranslatorService($container)));
    }
}
