<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImportLoggerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Markocupic\ImportFromCsvBundle\Logger\ImportLogger' shared autowired service.
     *
     * @return \Markocupic\ImportFromCsvBundle\Logger\ImportLogger
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/import-from-csv-bundle/src/Logger/ImportLogger.php';

        return $container->services['Markocupic\\ImportFromCsvBundle\\Logger\\ImportLogger'] = new \Markocupic\ImportFromCsvBundle\Logger\ImportLogger(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
