<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInitializeSystemListener3Service extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Markocupic\GalleryCreatorBundle\EventListener\ContaoHook\InitializeSystemListener' shared autowired service.
     *
     * @return \Markocupic\GalleryCreatorBundle\EventListener\ContaoHook\InitializeSystemListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/gallery-creator-bundle/src/EventListener/ContaoHook/InitializeSystemListener.php';

        return $container->services['Markocupic\\GalleryCreatorBundle\\EventListener\\ContaoHook\\InitializeSystemListener'] = new \Markocupic\GalleryCreatorBundle\EventListener\ContaoHook\InitializeSystemListener(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['contao.routing.scope_matcher'] ?? self::getContao_Routing_ScopeMatcherService($container)));
    }
}
