<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLeadService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Cgoit\LeadsOptinBundle\EventListener\DataContainer\Lead' shared autowired service.
     *
     * @return \Cgoit\LeadsOptinBundle\EventListener\DataContainer\Lead
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/cgoit/contao-leads-optin-bundle/src/EventListener/DataContainer/Lead.php';

        return $container->services['Cgoit\\LeadsOptinBundle\\EventListener\\DataContainer\\Lead'] = new \Cgoit\LeadsOptinBundle\EventListener\DataContainer\Lead();
    }
}
