<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLabelBuilderService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the private 'InspiredMinds\ContaoEventRegistration\EventRegistration\LabelBuilder' shared autowired service.
     *
     * @return \InspiredMinds\ContaoEventRegistration\EventRegistration\LabelBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/inspiredminds/contao-event-registration/src/EventRegistration/LabelBuilder.php';

        return $container->privates['InspiredMinds\\ContaoEventRegistration\\EventRegistration\\LabelBuilder'] = new \InspiredMinds\ContaoEventRegistration\EventRegistration\LabelBuilder(($container->services['contao.framework'] ?? self::getContao_FrameworkService($container)));
    }
}
