<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoadDataContainerListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'HeimrichHannot\MultiColumnEditorBundle\EventListener\Contao\LoadDataContainerListener' shared autowired service.
     *
     * @return \HeimrichHannot\MultiColumnEditorBundle\EventListener\Contao\LoadDataContainerListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/heimrichhannot/contao-multi-column-editor-bundle/src/EventListener/Contao/LoadDataContainerListener.php';

        return $container->services['HeimrichHannot\\MultiColumnEditorBundle\\EventListener\\Contao\\LoadDataContainerListener'] = new \HeimrichHannot\MultiColumnEditorBundle\EventListener\Contao\LoadDataContainerListener(($container->services['HeimrichHannot\\UtilsBundle\\Util\\Utils'] ?? self::getUtilsService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
