<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLanguageListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Terminal42\NotificationCenterBundle\EventListener\Backend\DataContainer\LanguageListener' shared service.
     *
     * @return \Terminal42\NotificationCenterBundle\EventListener\Backend\DataContainer\LanguageListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/notification_center/src/EventListener/Backend/DataContainer/GetCurrentRecordTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/notification_center/src/EventListener/Backend/DataContainer/LanguageListener.php';

        return $container->services['Terminal42\\NotificationCenterBundle\\EventListener\\Backend\\DataContainer\\LanguageListener'] = new \Terminal42\NotificationCenterBundle\EventListener\Backend\DataContainer\LanguageListener(($container->privates['Terminal42\\NotificationCenterBundle\\Backend\\AutoSuggester'] ?? $container->load('getAutoSuggesterService')), ($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)), ($container->privates['Terminal42\\NotificationCenterBundle\\Config\\ConfigLoader'] ?? $container->load('getConfigLoaderService')), ($container->services['contao.intl.locales'] ?? self::getContao_Intl_LocalesService($container)), ($container->services['translator'] ?? self::getTranslatorService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
