<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLeadsOptinNotificationService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the private 'Cgoit\LeadsOptinBundle\NotificationType\LeadsOptinNotification' shared autowired service.
     *
     * @return \Cgoit\LeadsOptinBundle\NotificationType\LeadsOptinNotification
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/notification_center/src/NotificationType/NotificationTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/cgoit/contao-leads-optin-bundle/src/NotificationType/LeadsOptinNotification.php';

        return $container->privates['Cgoit\\LeadsOptinBundle\\NotificationType\\LeadsOptinNotification'] = new \Cgoit\LeadsOptinBundle\NotificationType\LeadsOptinNotification(($container->privates['Terminal42\\NotificationCenterBundle\\Token\\Definition\\Factory\\ChainTokenDefinitionFactory'] ?? $container->load('getChainTokenDefinitionFactoryService')));
    }
}
