<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLeadSearchListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Terminal42\LeadsBundle\EventListener\DataContainer\LeadSearchListener' shared autowired service.
     *
     * @return \Terminal42\LeadsBundle\EventListener\DataContainer\LeadSearchListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-leads/src/EventListener/DataContainer/LeadSearchListener.php';

        return $container->services['Terminal42\\LeadsBundle\\EventListener\\DataContainer\\LeadSearchListener'] = new \Terminal42\LeadsBundle\EventListener\DataContainer\LeadSearchListener(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)));
    }
}
