<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMarkocupic_ImportFromCsv_Session_FactoryService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'markocupic.import_from_csv.session.factory' shared autowired service.
     *
     * @return \Markocupic\ImportFromCsvBundle\Session\SessionFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-foundation/Session/SessionFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/import-from-csv-bundle/src/Session/SessionFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/diversworld/contao-ducapp-bundle/src/Session/SessionFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/diversworld/contao-check-bundle/src/Session/SessionFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Session/SessionFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-foundation/Session/SessionFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-foundation/Session/Storage/SessionStorageFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorageFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-foundation/Session/SessionBagInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-foundation/Session/Storage/MetadataBag.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-foundation/Session/Attribute/AttributeBagInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-foundation/Session/Attribute/AttributeBag.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Session/Attribute/ArrayAttributeBag.php';
        include_once \dirname(__DIR__, 4).'/vendor/diversworld/contao-check-bundle/src/Session/Attribute/ArrayAttributeBag.php';
        include_once \dirname(__DIR__, 4).'/vendor/diversworld/contao-ducapp-bundle/src/Session/Attribute/ArrayAttributeBag.php';

        $a = ($container->privates['session_listener'] ?? self::getSessionListenerService($container));

        if (isset($container->services['markocupic.import_from_csv.session.factory'])) {
            return $container->services['markocupic.import_from_csv.session.factory'];
        }
        $b = new \Contao\CoreBundle\Session\Attribute\ArrayAttributeBag('_contao_be_attributes');
        $b->setName('contao_backend');
        $c = new \Contao\CoreBundle\Session\Attribute\ArrayAttributeBag('_contao_fe_attributes');
        $c->setName('contao_frontend');
        $d = new \Diversworld\ContaoCheckBundle\Session\Attribute\ArrayAttributeBag('_diversworld_contao_check_attributes');
        $d->setName('diversworld_contao_check');
        $e = new \Diversworld\ContaoDucappBundle\Session\Attribute\ArrayAttributeBag('_diversworld_contao_ducapp_attributes');
        $e->setName('diversworld_contao_ducapp');

        return $container->services['markocupic.import_from_csv.session.factory'] = new \Markocupic\ImportFromCsvBundle\Session\SessionFactory(new \Diversworld\ContaoDucappBundle\Session\SessionFactory(new \Diversworld\ContaoCheckBundle\Session\SessionFactory(new \Contao\CoreBundle\Session\SessionFactory(new \Symfony\Component\HttpFoundation\Session\SessionFactory(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), new \Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorageFactory($container->parameters['session.storage.options'], ($container->privates['session.handler.native'] ?? $container->load('getSession_Handler_NativeService')), new \Symfony\Component\HttpFoundation\Session\Storage\MetadataBag('_sf2_meta', 0), true), [$a, 'onSessionUsage']), $b, $c), $d), $e), ($container->services['markocupic.import_from_csv.session.attribute.array_attribute_bag'] ?? $container->load('getMarkocupic_ImportFromCsv_Session_Attribute_ArrayAttributeBagService')));
    }
}
