<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMountAppAjaxControllerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Markocupic\ImportFromCsvBundle\Contao\Controller\MountAppAjaxController' shared autowired service.
     *
     * @return \Markocupic\ImportFromCsvBundle\Contao\Controller\MountAppAjaxController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/import-from-csv-bundle/src/Contao/Controller/MountAppAjaxController.php';

        $container->services['Markocupic\\ImportFromCsvBundle\\Contao\\Controller\\MountAppAjaxController'] = $instance = new \Markocupic\ImportFromCsvBundle\Contao\Controller\MountAppAjaxController(($container->services['contao.csrf.token_manager'] ?? self::getContao_Csrf_TokenManagerService($container)), ($container->services['contao.framework'] ?? self::getContao_FrameworkService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['router'] ?? self::getRouterService($container)), \dirname(__DIR__, 4), 'contao_csrf_token', 25);

        $instance->setContainer($container);

        return $instance;
    }
}
