<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMarkocupicImportFromCsvBundleService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Markocupic\ImportFromCsvBundle\MarkocupicImportFromCsvBundle' shared autowired service.
     *
     * @return \Markocupic\ImportFromCsvBundle\MarkocupicImportFromCsvBundle
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Bundle/BundleInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Bundle/Bundle.php';
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/import-from-csv-bundle/src/MarkocupicImportFromCsvBundle.php';

        return $container->services['Markocupic\\ImportFromCsvBundle\\MarkocupicImportFromCsvBundle'] = new \Markocupic\ImportFromCsvBundle\MarkocupicImportFromCsvBundle();
    }
}
