<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMyCustomController2Service extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Diversworld\ContaoDucappBundle\Controller\MyCustomController' shared autowired service.
     *
     * @return \Diversworld\ContaoDucappBundle\Controller\MyCustomController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/diversworld/contao-ducapp-bundle/src/Controller/MyCustomController.php';

        $container->services['Diversworld\\ContaoDucappBundle\\Controller\\MyCustomController'] = $instance = new \Diversworld\ContaoDucappBundle\Controller\MyCustomController(($container->services['twig'] ?? self::getTwigService($container)));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('Diversworld\\ContaoDucappBundle\\Controller\\MyCustomController', $container));

        return $instance;
    }
}
