<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMceAssetsService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'HeimrichHannot\MultiColumnEditorBundle\Asset\MceAssets' shared autowired service.
     *
     * @return \HeimrichHannot\MultiColumnEditorBundle\Asset\MceAssets
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/heimrichhannot/contao-encore-contracts/PageAssetsTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/heimrichhannot/contao-multi-column-editor-bundle/src/Asset/MceAssets.php';

        $container->services['HeimrichHannot\\MultiColumnEditorBundle\\Asset\\MceAssets'] = $instance = new \HeimrichHannot\MultiColumnEditorBundle\Asset\MceAssets(($container->services['HeimrichHannot\\UtilsBundle\\Util\\Utils'] ?? self::getUtilsService($container)));

        $instance->setContainer(($container->privates['.service_locator.Xbsa8iG'] ??= new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [], []))->withContext('HeimrichHannot\\MultiColumnEditorBundle\\Asset\\MceAssets', $container));

        return $instance;
    }
}
