<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewsCategoriesManagerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Codefog\NewsCategoriesBundle\NewsCategoriesManager' shared autowired service.
     *
     * @return \Codefog\NewsCategoriesBundle\NewsCategoriesManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/codefog/contao-news_categories/src/NewsCategoriesManager.php';

        return $container->services['Codefog\\NewsCategoriesBundle\\NewsCategoriesManager'] = new \Codefog\NewsCategoriesBundle\NewsCategoriesManager(($container->services['contao.framework'] ?? self::getContao_FrameworkService($container)), \dirname(__DIR__, 4));
    }
}
