<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewsletterUnsubscribeNotificationTypeService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the private 'Terminal42\NotificationCenterBundle\NotificationType\Newsletter\NewsletterUnsubscribeNotificationType' shared service.
     *
     * @return \Terminal42\NotificationCenterBundle\NotificationType\Newsletter\NewsletterUnsubscribeNotificationType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/notification_center/src/NotificationType/NotificationTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/notification_center/src/NotificationType/Newsletter/NewsletterUnsubscribeNotificationType.php';

        return $container->privates['Terminal42\\NotificationCenterBundle\\NotificationType\\Newsletter\\NewsletterUnsubscribeNotificationType'] = new \Terminal42\NotificationCenterBundle\NotificationType\Newsletter\NewsletterUnsubscribeNotificationType(($container->privates['Terminal42\\NotificationCenterBundle\\Token\\Definition\\Factory\\ChainTokenDefinitionFactory'] ?? $container->load('getChainTokenDefinitionFactoryService')));
    }
}
