<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewsCategoryAliasListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Codefog\NewsCategoriesBundle\EventListener\DataContainer\NewsCategoryAliasListener' shared autowired service.
     *
     * @return \Codefog\NewsCategoriesBundle\EventListener\DataContainer\NewsCategoryAliasListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/codefog/contao-news_categories/src/EventListener/DataContainer/NewsCategoryAliasListener.php';

        return $container->services['Codefog\\NewsCategoriesBundle\\EventListener\\DataContainer\\NewsCategoryAliasListener'] = new \Codefog\NewsCategoriesBundle\EventListener\DataContainer\NewsCategoryAliasListener(($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)), ($container->services['contao.slug'] ?? $container->load('getContao_SlugService')));
    }
}
