<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNoCookiebarSpecifiedExceptionService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Oveleon\ContaoCookiebar\Exception\NoCookiebarSpecifiedException' shared autowired service.
     *
     * @return \Oveleon\ContaoCookiebar\Exception\NoCookiebarSpecifiedException
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/oveleon/contao-cookiebar/src/Exception/NoCookiebarSpecifiedException.php';

        return $container->services['Oveleon\\ContaoCookiebar\\Exception\\NoCookiebarSpecifiedException'] = new \Oveleon\ContaoCookiebar\Exception\NoCookiebarSpecifiedException();
    }
}
