<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewsCategoriesVoterService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the private '.debug.security.voter.Codefog\NewsCategoriesBundle\Security\Voter\DataContainer\NewsCategoriesVoter' shared service.
     *
     * @return \Symfony\Component\Security\Core\Authorization\Voter\TraceableVoter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/Authorization/Voter/TraceableVoter.php';
        include_once \dirname(__DIR__, 4).'/vendor/codefog/contao-news_categories/src/Security/Voter/DataContainer/NewsCategoriesVoter.php';

        $a = ($container->services['security.helper'] ?? self::getSecurity_HelperService($container));

        if (isset($container->privates['.debug.security.voter.Codefog\\NewsCategoriesBundle\\Security\\Voter\\DataContainer\\NewsCategoriesVoter'])) {
            return $container->privates['.debug.security.voter.Codefog\\NewsCategoriesBundle\\Security\\Voter\\DataContainer\\NewsCategoriesVoter'];
        }
        $b = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['.debug.security.voter.Codefog\\NewsCategoriesBundle\\Security\\Voter\\DataContainer\\NewsCategoriesVoter'])) {
            return $container->privates['.debug.security.voter.Codefog\\NewsCategoriesBundle\\Security\\Voter\\DataContainer\\NewsCategoriesVoter'];
        }

        return $container->privates['.debug.security.voter.Codefog\\NewsCategoriesBundle\\Security\\Voter\\DataContainer\\NewsCategoriesVoter'] = new \Symfony\Component\Security\Core\Authorization\Voter\TraceableVoter(new \Codefog\NewsCategoriesBundle\Security\Voter\DataContainer\NewsCategoriesVoter($a, ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack())), $b);
    }
}
