<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewsFeedListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the private 'Codefog\NewsCategoriesBundle\EventListener\NewsFeedListener' shared autowired service.
     *
     * @return \Codefog\NewsCategoriesBundle\EventListener\NewsFeedListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/codefog/contao-news_categories/src/EventListener/NewsFeedListener.php';

        return $container->privates['Codefog\\NewsCategoriesBundle\\EventListener\\NewsFeedListener'] = new \Codefog\NewsCategoriesBundle\EventListener\NewsFeedListener(($container->services['translator'] ?? self::getTranslatorService($container)));
    }
}
