<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotificationOptionsListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Terminal42\NewsNewsletterBundle\EventListener\NotificationOptionsListener' shared autowired service.
     *
     * @return \Terminal42\NewsNewsletterBundle\EventListener\NotificationOptionsListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-news_newsletter/src/EventListener/NotificationOptionsListener.php';

        return $container->services['Terminal42\\NewsNewsletterBundle\\EventListener\\NotificationOptionsListener'] = new \Terminal42\NewsNewsletterBundle\EventListener\NotificationOptionsListener(($container->privates['Terminal42\\NotificationCenterBundle\\NotificationCenter'] ?? $container->load('getNotificationCenterService')));
    }
}
