<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewsDefaultCategoriesListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Codefog\NewsCategoriesBundle\EventListener\DataContainer\NewsDefaultCategoriesListener' shared autowired service.
     *
     * @return \Codefog\NewsCategoriesBundle\EventListener\DataContainer\NewsDefaultCategoriesListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/codefog/contao-news_categories/src/EventListener/DataContainer/NewsDefaultCategoriesListener.php';

        return $container->services['Codefog\\NewsCategoriesBundle\\EventListener\\DataContainer\\NewsDefaultCategoriesListener'] = new \Codefog\NewsCategoriesBundle\EventListener\DataContainer\NewsDefaultCategoriesListener(($container->services['Codefog\\HasteBundle\\DcaRelationsManager'] ?? $container->load('getDcaRelationsManagerService')), ($container->services['security.helper'] ?? self::getSecurity_HelperService($container)));
    }
}
