<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProcessFormDataListener3Service extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Terminal42\LeadsBundle\EventListener\ProcessFormDataListener' shared autowired service.
     *
     * @return \Terminal42\LeadsBundle\EventListener\ProcessFormDataListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-leads/src/EventListener/ProcessFormDataListener.php';

        return $container->services['Terminal42\\LeadsBundle\\EventListener\\ProcessFormDataListener'] = new \Terminal42\LeadsBundle\EventListener\ProcessFormDataListener(($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)), ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container)));
    }
}
