<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPictureUtilService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Markocupic\GalleryCreatorBundle\Util\PictureUtil' shared autowired service.
     *
     * @return \Markocupic\GalleryCreatorBundle\Util\PictureUtil
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/gallery-creator-bundle/src/Util/PictureUtil.php';

        return $container->services['Markocupic\\GalleryCreatorBundle\\Util\\PictureUtil'] = new \Markocupic\GalleryCreatorBundle\Util\PictureUtil(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['contao.routing.scope_matcher'] ?? self::getContao_Routing_ScopeMatcherService($container)), ($container->services['contao.image.studio'] ?? $container->load('getContao_Image_StudioService')), ($container->privates['contao.filesystem.virtual.files'] ?? $container->load('getContao_Filesystem_Virtual_FilesService')), false, \dirname(__DIR__, 4));
    }
}
