<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPageTypeAccessVoterService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the private 'Terminal42\FolderpageBundle\Voter\PageTypeAccessVoter' shared autowired service.
     *
     * @return \Terminal42\FolderpageBundle\Voter\PageTypeAccessVoter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-folderpage/src/Voter/PageTypeAccessVoter.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Security/Voter/DataContainer/AbstractDataContainerVoter.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Security/Voter/DataContainer/TypeAccessTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Security/Voter/DataContainer/PageTypeAccessVoter.php';

        $a = ($container->privates['debug.security.access.decision_manager'] ?? self::getDebug_Security_Access_DecisionManagerService($container));

        if (isset($container->privates['Terminal42\\FolderpageBundle\\Voter\\PageTypeAccessVoter'])) {
            return $container->privates['Terminal42\\FolderpageBundle\\Voter\\PageTypeAccessVoter'];
        }
        $b = ($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container));

        if (isset($container->privates['Terminal42\\FolderpageBundle\\Voter\\PageTypeAccessVoter'])) {
            return $container->privates['Terminal42\\FolderpageBundle\\Voter\\PageTypeAccessVoter'];
        }

        return $container->privates['Terminal42\\FolderpageBundle\\Voter\\PageTypeAccessVoter'] = new \Terminal42\FolderpageBundle\Voter\PageTypeAccessVoter(new \Contao\CoreBundle\Security\Voter\DataContainer\PageTypeAccessVoter($a, $b), $a, $b);
    }
}
