<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProcessFormDataListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Cgoit\FormFillPdfBundle\EventListener\ProcessFormDataListener' shared autowired service.
     *
     * @return \Cgoit\FormFillPdfBundle\EventListener\ProcessFormDataListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/cgoit/contao-form-fill-pdf-bundle/src/EventListener/ProcessFormDataListener.php';

        return $container->services['Cgoit\\FormFillPdfBundle\\EventListener\\ProcessFormDataListener'] = new \Cgoit\FormFillPdfBundle\EventListener\ProcessFormDataListener(($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)));
    }
}
