<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPageStatusIconListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Terminal42\FolderpageBundle\EventListener\PageStatusIconListener' shared autowired service.
     *
     * @return \Terminal42\FolderpageBundle\EventListener\PageStatusIconListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-folderpage/src/EventListener/PageStatusIconListener.php';

        return $container->services['Terminal42\\FolderpageBundle\\EventListener\\PageStatusIconListener'] = new \Terminal42\FolderpageBundle\EventListener\PageStatusIconListener();
    }
}
