<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParseWidgetListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'InspiredMinds\ContaoBackendFormsBundle\EventListener\ParseWidgetListener' shared service.
     *
     * @return \InspiredMinds\ContaoBackendFormsBundle\EventListener\ParseWidgetListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/inspiredminds/contao-backend-forms/src/EventListener/ParseWidgetListener.php';

        return $container->services['InspiredMinds\\ContaoBackendFormsBundle\\EventListener\\ParseWidgetListener'] = new \InspiredMinds\ContaoBackendFormsBundle\EventListener\ParseWidgetListener();
    }
}
