<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlugin2Service extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Markocupic\ImportFromCsvBundle\ContaoManager\Plugin' shared autowired service.
     *
     * @return \Markocupic\ImportFromCsvBundle\ContaoManager\Plugin
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao/manager-plugin/src/Bundle/BundlePluginInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/import-from-csv-bundle/src/ContaoManager/Plugin.php';

        return $container->services['Markocupic\\ImportFromCsvBundle\\ContaoManager\\Plugin'] = new \Markocupic\ImportFromCsvBundle\ContaoManager\Plugin();
    }
}
