<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPageCallbackListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Oveleon\ContaoCookiebar\EventListener\DataContainer\PageCallbackListener' shared autowired service.
     *
     * @return \Oveleon\ContaoCookiebar\EventListener\DataContainer\PageCallbackListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/oveleon/contao-cookiebar/src/EventListener/DataContainer/PageCallbackListener.php';

        return $container->services['Oveleon\\ContaoCookiebar\\EventListener\\DataContainer\\PageCallbackListener'] = new \Oveleon\ContaoCookiebar\EventListener\DataContainer\PageCallbackListener();
    }
}
