<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParseTemplateListener2Service extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Tastaturberuf\ContaoImageCopyrightBundle\EventListener\ParseTemplateListener' shared autowired service.
     *
     * @return \Tastaturberuf\ContaoImageCopyrightBundle\EventListener\ParseTemplateListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/tastaturberuf/contao-image-copyright-bundle/EventListener/ParseTemplateListener.php';

        return $container->services['Tastaturberuf\\ContaoImageCopyrightBundle\\EventListener\\ParseTemplateListener'] = new \Tastaturberuf\ContaoImageCopyrightBundle\EventListener\ParseTemplateListener(($container->services['contao.routing.scope_matcher'] ?? self::getContao_Routing_ScopeMatcherService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
