<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrepareFormDataHookService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Cgoit\LeadsOptinBundle\Hook\PrepareFormDataHook' shared autowired service.
     *
     * @return \Cgoit\LeadsOptinBundle\Hook\PrepareFormDataHook
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/cgoit/contao-leads-optin-bundle/src/Hook/PrepareFormDataHook.php';

        return $container->services['Cgoit\\LeadsOptinBundle\\Hook\\PrepareFormDataHook'] = new \Cgoit\LeadsOptinBundle\Hook\PrepareFormDataHook();
    }
}
