<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSendEmailConfirmControllerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Markocupic\BackendPasswordRecoveryBundle\Controller\SendEmailConfirmController' shared autowired service.
     *
     * @return \Markocupic\BackendPasswordRecoveryBundle\Controller\SendEmailConfirmController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/backend-password-recovery-bundle/src/Controller/BackendTemplateTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/backend-password-recovery-bundle/src/Controller/SendEmailConfirmController.php';
        include_once \dirname(__DIR__, 4).'/vendor/code4nix/uri-signer/src/UriSigner.php';

        $container->services['Markocupic\\BackendPasswordRecoveryBundle\\Controller\\SendEmailConfirmController'] = $instance = new \Markocupic\BackendPasswordRecoveryBundle\Controller\SendEmailConfirmController(($container->services['contao.framework'] ?? self::getContao_FrameworkService($container)), ($container->services['router'] ?? self::getRouterService($container)), ($container->services['code4nix_uri_signer.uri_signer'] ??= new \Code4Nix\UriSigner\UriSigner($container->getEnv('APP_SECRET'), '_hash', 3600)));

        $instance->setContainer(($container->privates['.service_locator.HuDo1n.'] ?? $container->load('get_ServiceLocator_HuDo1n_Service'))->withContext('Markocupic\\BackendPasswordRecoveryBundle\\Controller\\SendEmailConfirmController', $container));

        return $instance;
    }
}
