<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSerializedStorageFactoryService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the private 'Mvo\ContaoGroupWidget\Storage\SerializedStorageFactory' shared service.
     *
     * @return \Mvo\ContaoGroupWidget\Storage\SerializedStorageFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/mvo/contao-group-widget/src/Storage/StorageFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/mvo/contao-group-widget/src/Storage/SerializedStorageFactory.php';

        return $container->privates['Mvo\\ContaoGroupWidget\\Storage\\SerializedStorageFactory'] = new \Mvo\ContaoGroupWidget\Storage\SerializedStorageFactory(($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)));
    }
}
