<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTerminal42Node_Listener_InsertTagsService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'terminal42_node.listener.insert_tags' shared service.
     *
     * @return \Terminal42\NodeBundle\EventListener\InsertTagsListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-node/src/EventListener/InsertTagsListener.php';
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-node/src/NodeManager.php';

        return $container->services['terminal42_node.listener.insert_tags'] = new \Terminal42\NodeBundle\EventListener\InsertTagsListener(($container->services['terminal42_node.manager'] ??= new \Terminal42\NodeBundle\NodeManager()), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
