<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTerminal42Leads_FormattersService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the private 'terminal42_leads.formatters' shared autowired service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['terminal42_leads.formatters'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'date' => ['privates', 'Terminal42\\LeadsBundle\\Export\\Format\\DateFormatter', 'getDateFormatterService', true],
            'datim' => ['privates', 'Terminal42\\LeadsBundle\\Export\\Format\\DateFormatter', 'getDateFormatterService', true],
            'time' => ['privates', 'Terminal42\\LeadsBundle\\Export\\Format\\DateFormatter', 'getDateFormatterService', true],
            'uuidToFilePath' => ['privates', 'Terminal42\\LeadsBundle\\Export\\Format\\UuidToFilePathFormatter', 'getUuidToFilePathFormatterService', true],
            'yesno' => ['privates', 'Terminal42\\LeadsBundle\\Export\\Format\\YesnoFormatter', 'getYesnoFormatterService', true],
        ], [
            'date' => 'Terminal42\\LeadsBundle\\Export\\Format\\DateFormatter',
            'datim' => 'Terminal42\\LeadsBundle\\Export\\Format\\DateFormatter',
            'time' => 'Terminal42\\LeadsBundle\\Export\\Format\\DateFormatter',
            'uuidToFilePath' => 'Terminal42\\LeadsBundle\\Export\\Format\\UuidToFilePathFormatter',
            'yesno' => 'Terminal42\\LeadsBundle\\Export\\Format\\YesnoFormatter',
        ]);
    }
}
