<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserUtilService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the private 'HeimrichHannot\UtilsBundle\Util\UserUtil' shared autowired service.
     *
     * @return \HeimrichHannot\UtilsBundle\Util\UserUtil
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/heimrichhannot/contao-utils-bundle/src/Util/UserUtil.php';
        include_once \dirname(__DIR__, 4).'/vendor/heimrichhannot/contao-utils-bundle/src/Util/DatabaseUtil.php';

        $a = ($container->privates['HeimrichHannot\\UtilsBundle\\Util\\ModelUtil'] ?? $container->load('getModelUtilService'));

        if (isset($container->privates['HeimrichHannot\\UtilsBundle\\Util\\UserUtil'])) {
            return $container->privates['HeimrichHannot\\UtilsBundle\\Util\\UserUtil'];
        }

        return $container->privates['HeimrichHannot\\UtilsBundle\\Util\\UserUtil'] = new \HeimrichHannot\UtilsBundle\Util\UserUtil($a, ($container->privates['HeimrichHannot\\UtilsBundle\\Util\\DatabaseUtil'] ??= new \HeimrichHannot\UtilsBundle\Util\DatabaseUtil()), ($container->services['contao.framework'] ?? self::getContao_FrameworkService($container)));
    }
}
