<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUpdatePersonalDataListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Terminal42\NotificationCenterBundle\EventListener\UpdatePersonalDataListener' shared service.
     *
     * @return \Terminal42\NotificationCenterBundle\EventListener\UpdatePersonalDataListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/notification_center/src/EventListener/UpdatePersonalDataListener.php';

        return $container->services['Terminal42\\NotificationCenterBundle\\EventListener\\UpdatePersonalDataListener'] = new \Terminal42\NotificationCenterBundle\EventListener\UpdatePersonalDataListener(($container->privates['Terminal42\\NotificationCenterBundle\\NotificationCenter'] ?? $container->load('getNotificationCenterService')), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['Codefog\\HasteBundle\\Formatter'] ?? $container->load('getFormatterService')), ($container->services['contao.routing.scope_matcher'] ?? self::getContao_Routing_ScopeMatcherService($container)), ($container->services['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)), ($container->services['twig'] ?? self::getTwigService($container)));
    }
}
