<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVisitorCalculatorService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'BugBuster\VisitorsBundle\Classes\VisitorCalculator' shared autowired service.
     *
     * @return \BugBuster\VisitorsBundle\Classes\VisitorCalculator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/bugbuster/contao-visitors-bundle/src/Classes/VisitorCalculator.php';

        return $container->services['BugBuster\\VisitorsBundle\\Classes\\VisitorCalculator'] = new \BugBuster\VisitorsBundle\Classes\VisitorCalculator(($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)));
    }
}
