<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVisitorsFeControllerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'BugBuster\VisitorsBundle\Controller\VisitorsFeController' shared autowired service.
     *
     * @return \BugBuster\VisitorsBundle\Controller\VisitorsFeController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/bugbuster/contao-visitors-bundle/src/Controller/VisitorsFeController.php';

        $container->services['BugBuster\\VisitorsBundle\\Controller\\VisitorsFeController'] = $instance = new \BugBuster\VisitorsBundle\Controller\VisitorsFeController();

        $instance->setContainer($container);

        return $instance;
    }
}
