<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVisitorsFrontendControllerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'BugBuster\VisitorsBundle\Controller\FrontendModule\VisitorsFrontendController' shared autowired service.
     *
     * @return \BugBuster\VisitorsBundle\Controller\FrontendModule\VisitorsFrontendController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Fragment/FragmentOptionsAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Controller/AbstractFragmentController.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Controller/FrontendModule/AbstractFrontendModuleController.php';
        include_once \dirname(__DIR__, 4).'/vendor/bugbuster/contao-visitors-bundle/src/Controller/FrontendModule/VisitorsFrontendController.php';

        $container->services['BugBuster\\VisitorsBundle\\Controller\\FrontendModule\\VisitorsFrontendController'] = $instance = new \BugBuster\VisitorsBundle\Controller\FrontendModule\VisitorsFrontendController();

        $instance->setContainer(($container->privates['.service_locator.UH.gGKG'] ?? $container->load('get_ServiceLocator_UH_GGKGService'))->withContext('BugBuster\\VisitorsBundle\\Controller\\FrontendModule\\VisitorsFrontendController', $container));

        return $instance;
    }
}
