<?php

namespace ContainerXCjKscP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVersion5MigrationService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Markocupic\ImportFromCsvBundle\Migration\Version5Migration' shared autowired service.
     *
     * @return \Markocupic\ImportFromCsvBundle\Migration\Version5Migration
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Migration/MigrationInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Migration/AbstractMigration.php';
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/import-from-csv-bundle/src/Migration/Version5Migration.php';

        return $container->services['Markocupic\\ImportFromCsvBundle\\Migration\\Version5Migration'] = new \Markocupic\ImportFromCsvBundle\Migration\Version5Migration(($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)));
    }
}
