<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI4Xk6xX\Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI4Xk6xX/Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerI4Xk6xX.legacy');

    return;
}

if (!\class_exists(Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerI4Xk6xX\Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer::class, Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer::class, false);
}

return new \ContainerI4Xk6xX\Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer([
    'container.build_hash' => 'I4Xk6xX',
    'container.build_id' => '1cb166b0',
    'container.build_time' => 1734697173,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI4Xk6xX');
