<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8qMG6Zg\Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8qMG6Zg/Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8qMG6Zg.legacy');

    return;
}

if (!\class_exists(Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer::class, false)) {
    \class_alias(\Container8qMG6Zg\Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer::class, Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer::class, false);
}

return new \Container8qMG6Zg\Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer([
    'container.build_hash' => '8qMG6Zg',
    'container.build_id' => '7fb91afa',
    'container.build_time' => 1735032389,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container8qMG6Zg');
