<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NqgdEu8_Contao_Fragment_Contao_FrontendModule_PageimageService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the private '.service_locator.nqgdEu8.contao.fragment._contao.frontend_module.pageimage' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return ($container->privates['.service_locator.nqgdEu8'] ?? $container->load('get_ServiceLocator_NqgdEu8Service'))->withContext('contao.fragment._contao.frontend_module.pageimage', $container);
    }
}
