<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9iwrGHbService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the private '.service_locator.9iwrGHb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9iwrGHb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'album' => ['privates', '.errored..service_locator.9iwrGHb.Markocupic\\GalleryCreatorBundle\\Model\\GalleryCreatorAlbumsModel', NULL, 'Cannot autowire service ".service_locator.9iwrGHb": it needs an instance of "Markocupic\\GalleryCreatorBundle\\Model\\GalleryCreatorAlbumsModel" but this type has been excluded in "config/services.yaml".'],
        ], [
            'album' => 'Markocupic\\GalleryCreatorBundle\\Model\\GalleryCreatorAlbumsModel',
        ]);
    }
}
