<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddNewsletterSubscriptionListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Markocupic\ImportFromCsvBundle\EventListener\PostImport\AddNewsletterSubscriptionListener' shared autowired service.
     *
     * @return \Markocupic\ImportFromCsvBundle\EventListener\PostImport\AddNewsletterSubscriptionListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/import-from-csv-bundle/src/EventListener/PostImport/AddNewsletterSubscriptionListener.php';

        $a = ($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container));

        if (isset($container->services['Markocupic\\ImportFromCsvBundle\\EventListener\\PostImport\\AddNewsletterSubscriptionListener'])) {
            return $container->services['Markocupic\\ImportFromCsvBundle\\EventListener\\PostImport\\AddNewsletterSubscriptionListener'];
        }

        return $container->services['Markocupic\\ImportFromCsvBundle\\EventListener\\PostImport\\AddNewsletterSubscriptionListener'] = new \Markocupic\ImportFromCsvBundle\EventListener\PostImport\AddNewsletterSubscriptionListener(($container->services['contao.framework'] ?? self::getContao_FrameworkService($container)), $a);
    }
}
