<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAccordionUtilService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the private 'HeimrichHannot\UtilsBundle\Util\AccordionUtil' shared autowired service.
     *
     * @return \HeimrichHannot\UtilsBundle\Util\AccordionUtil
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/heimrichhannot/contao-utils-bundle/src/Util/AccordionUtil.php';

        return $container->privates['HeimrichHannot\\UtilsBundle\\Util\\AccordionUtil'] = new \HeimrichHannot\UtilsBundle\Util\AccordionUtil(($container->services['contao.framework'] ?? self::getContao_FrameworkService($container)));
    }
}
