<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdvancedClasses_Listener_DataContainer_ContentService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'advanced_classes.listener.data_container.content' shared service.
     *
     * @return \ContaoDD\AdvancedClassesBundle\EventListener\DataContainer\ContentListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao-dd/advanced-classes-bundle/src/EventListener/DataContainer/ListenerHelperTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao-dd/advanced-classes-bundle/src/EventListener/DataContainer/ContentListener.php';

        return $container->services['advanced_classes.listener.data_container.content'] = new \ContaoDD\AdvancedClassesBundle\EventListener\DataContainer\ContentListener(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
