<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArrayUtilService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the private 'HeimrichHannot\UtilsBundle\Util\ArrayUtil' shared autowired service.
     *
     * @return \HeimrichHannot\UtilsBundle\Util\ArrayUtil
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/heimrichhannot/contao-utils-bundle/src/Util/ArrayUtil.php';

        return $container->privates['HeimrichHannot\\UtilsBundle\\Util\\ArrayUtil'] = new \HeimrichHannot\UtilsBundle\Util\ArrayUtil();
    }
}
