<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddEventDataListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the private 'InspiredMinds\ContaoEventRegistration\EventListener\NotificationCenter\AddEventDataListener' shared autowired service.
     *
     * @return \InspiredMinds\ContaoEventRegistration\EventListener\NotificationCenter\AddEventDataListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/inspiredminds/contao-event-registration/src/EventListener/NotificationCenter/AddEventDataListener.php';

        $a = ($container->privates['InspiredMinds\\ContaoEventRegistration\\EventRegistration'] ?? $container->load('getEventRegistrationService'));

        if (isset($container->privates['InspiredMinds\\ContaoEventRegistration\\EventListener\\NotificationCenter\\AddEventDataListener'])) {
            return $container->privates['InspiredMinds\\ContaoEventRegistration\\EventListener\\NotificationCenter\\AddEventDataListener'];
        }

        return $container->privates['InspiredMinds\\ContaoEventRegistration\\EventListener\\NotificationCenter\\AddEventDataListener'] = new \InspiredMinds\ContaoEventRegistration\EventListener\NotificationCenter\AddEventDataListener($a, ($container->privates['Terminal42\\NotificationCenterBundle\\Token\\Definition\\Factory\\ChainTokenDefinitionFactory'] ?? $container->load('getChainTokenDefinitionFactoryService')));
    }
}
