<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActivationListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Terminal42\NotificationCenterBundle\EventListener\Newsletter\ActivationListener' shared service.
     *
     * @return \Terminal42\NotificationCenterBundle\EventListener\Newsletter\ActivationListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/notification_center/src/EventListener/Newsletter/ActivationListener.php';

        return $container->services['Terminal42\\NotificationCenterBundle\\EventListener\\Newsletter\\ActivationListener'] = new \Terminal42\NotificationCenterBundle\EventListener\Newsletter\ActivationListener(($container->privates['Terminal42\\NotificationCenterBundle\\NotificationCenter'] ?? $container->load('getNotificationCenterService')), ($container->services['contao.framework'] ?? self::getContao_FrameworkService($container)));
    }
}
