<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAlbumVoterService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Markocupic\GalleryCreatorBundle\Security\Voter\AlbumVoter' shared autowired service.
     *
     * @return \Markocupic\GalleryCreatorBundle\Security\Voter\AlbumVoter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/Authorization/Voter/Voter.php';
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/gallery-creator-bundle/src/Security/Voter/AlbumVoter.php';

        return $container->services['Markocupic\\GalleryCreatorBundle\\Security\\Voter\\AlbumVoter'] = new \Markocupic\GalleryCreatorBundle\Security\Voter\AlbumVoter(($container->services['contao.framework'] ?? self::getContao_FrameworkService($container)));
    }
}
