<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAjaxManagerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'HeimrichHannot\AjaxBundle\Manager\AjaxManager' shared autowired service.
     *
     * @return \HeimrichHannot\AjaxBundle\Manager\AjaxManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/heimrichhannot/contao-ajax-bundle/src/Manager/AjaxManager.php';

        return $container->services['HeimrichHannot\\AjaxBundle\\Manager\\AjaxManager'] = new \HeimrichHannot\AjaxBundle\Manager\AjaxManager(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['contao.routing.scope_matcher'] ?? self::getContao_Routing_ScopeMatcherService($container)), ($container->services['contao.csrf.token_manager'] ?? self::getContao_Csrf_TokenManagerService($container)));
    }
}
