<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBulkyItemsTokenListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the private 'Terminal42\NotificationCenterBundle\EventListener\BulkyItemsTokenListener' shared service.
     *
     * @return \Terminal42\NotificationCenterBundle\EventListener\BulkyItemsTokenListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/notification_center/src/EventListener/BulkyItemsTokenListener.php';

        $a = ($container->services['twig'] ?? self::getTwigService($container));

        if (isset($container->privates['Terminal42\\NotificationCenterBundle\\EventListener\\BulkyItemsTokenListener'])) {
            return $container->privates['Terminal42\\NotificationCenterBundle\\EventListener\\BulkyItemsTokenListener'];
        }

        return $container->privates['Terminal42\\NotificationCenterBundle\\EventListener\\BulkyItemsTokenListener'] = new \Terminal42\NotificationCenterBundle\EventListener\BulkyItemsTokenListener(($container->privates['Terminal42\\NotificationCenterBundle\\BulkyItem\\BulkyItemStorage'] ?? $container->load('getBulkyItemStorageService')), ($container->privates['Terminal42\\NotificationCenterBundle\\Token\\Definition\\Factory\\ChainTokenDefinitionFactory'] ?? $container->load('getChainTokenDefinitionFactoryService')), $a);
    }
}
