<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBackendUiUtilService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the private 'HeimrichHannot\UtilsBundle\Util\BackendUiUtil' shared autowired service.
     *
     * @return \HeimrichHannot\UtilsBundle\Util\BackendUiUtil
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/heimrichhannot/contao-utils-bundle/src/Util/BackendUiUtil.php';
        include_once \dirname(__DIR__, 4).'/vendor/heimrichhannot/contao-utils-bundle/src/Util/HtmlUtil.php';

        $a = ($container->privates['HeimrichHannot\\UtilsBundle\\Util\\RoutingUtil'] ?? $container->load('getRoutingUtilService'));

        if (isset($container->privates['HeimrichHannot\\UtilsBundle\\Util\\BackendUiUtil'])) {
            return $container->privates['HeimrichHannot\\UtilsBundle\\Util\\BackendUiUtil'];
        }

        return $container->privates['HeimrichHannot\\UtilsBundle\\Util\\BackendUiUtil'] = new \HeimrichHannot\UtilsBundle\Util\BackendUiUtil($a, ($container->services['contao.framework'] ?? self::getContao_FrameworkService($container)), ($container->privates['HeimrichHannot\\UtilsBundle\\Util\\HtmlUtil'] ??= new \HeimrichHannot\UtilsBundle\Util\HtmlUtil()));
    }
}
