<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBackendUsabilityListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Pdir\ContaoWebtoolsBundle\EventListener\DataContainer\BackendUsabilityListener' shared autowired service.
     *
     * @return \Pdir\ContaoWebtoolsBundle\EventListener\DataContainer\BackendUsabilityListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pdir/contao-webtools/src/EventListener/DataContainer/BackendUsabilityListener.php';

        return $container->services['Pdir\\ContaoWebtoolsBundle\\EventListener\\DataContainer\\BackendUsabilityListener'] = new \Pdir\ContaoWebtoolsBundle\EventListener\DataContainer\BackendUsabilityListener();
    }
}
