<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBackupDbControllerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Softleister\BackupDbBundle\Controller\BackupDbController' shared service.
     *
     * @return \Softleister\BackupDbBundle\Controller\BackupDbController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/do-while/contao-backupdb-bundle/src/Controller/BackupDbController.php';

        return $container->services['Softleister\\BackupDbBundle\\Controller\\BackupDbController'] = new \Softleister\BackupDbBundle\Controller\BackupDbController(($container->services['contao.framework'] ?? self::getContao_FrameworkService($container)));
    }
}
