<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCsvExporter2Service extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the private 'Terminal42\LeadsBundle\Export\CsvExporter' shared autowired service.
     *
     * @return \Terminal42\LeadsBundle\Export\CsvExporter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-leads/src/Export/ExporterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-leads/src/Export/AbstractExporter.php';
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-leads/src/Export/CsvExporter.php';

        return $container->privates['Terminal42\\LeadsBundle\\Export\\CsvExporter'] = new \Terminal42\LeadsBundle\Export\CsvExporter(($container->privates['terminal42_leads.formatters'] ?? $container->load('getTerminal42Leads_FormattersService')), ($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)), ($container->services['translator'] ?? self::getTranslatorService($container)), ($container->services['Codefog\\HasteBundle\\StringParser'] ?? $container->load('getStringParserService')), ($container->privates['terminal42_leads.expression_language'] ?? $container->load('getTerminal42Leads_ExpressionLanguageService')));
    }
}
