<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContao_Fragment_Contao_FrontendModule_ImageCopyrightListService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'contao.fragment._contao.frontend_module.image_copyright_list' shared autowired service.
     *
     * @return \Tastaturberuf\ContaoImageCopyrightBundle\Controller\ImageCopyrightListController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Fragment/FragmentOptionsAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Controller/AbstractFragmentController.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Controller/FrontendModule/AbstractFrontendModuleController.php';
        include_once \dirname(__DIR__, 4).'/vendor/tastaturberuf/contao-image-copyright-bundle/Controller/ImageCopyrightListController.php';

        $container->services['contao.fragment._contao.frontend_module.image_copyright_list'] = $instance = new \Tastaturberuf\ContaoImageCopyrightBundle\Controller\ImageCopyrightListController(($container->services['contao.image.factory'] ?? $container->load('getContao_Image_FactoryService')), \dirname(__DIR__, 4), $container->parameters['contao.image.valid_extensions']);

        $instance->setFragmentOptions(['type' => 'image_copyright_list', 'category' => 'miscellaneous', 'template' => 'mod_image_copyright_list', 'method' => NULL, 'renderer' => NULL, 'priority' => 0, 'debugController' => 'Tastaturberuf\\ContaoImageCopyrightBundle\\Controller\\ImageCopyrightListController']);
        $instance->setContainer(($container->privates['.service_locator.nqgdEu8'] ?? $container->load('get_ServiceLocator_NqgdEu8Service'))->withContext('contao.fragment._contao.frontend_module.image_copyright_list', $container));

        return $instance;
    }
}
