<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCookiebarOpenerControllerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Oveleon\ContaoCookiebar\Controller\ContentElement\CookiebarOpenerController' shared autowired service.
     *
     * @return \Oveleon\ContaoCookiebar\Controller\ContentElement\CookiebarOpenerController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Fragment/FragmentOptionsAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Controller/AbstractFragmentController.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Controller/ContentElement/AbstractContentElementController.php';
        include_once \dirname(__DIR__, 4).'/vendor/oveleon/contao-cookiebar/src/Controller/ContentElement/CookiebarOpenerController.php';

        $container->services['Oveleon\\ContaoCookiebar\\Controller\\ContentElement\\CookiebarOpenerController'] = $instance = new \Oveleon\ContaoCookiebar\Controller\ContentElement\CookiebarOpenerController(($container->services['translator'] ?? self::getTranslatorService($container)));

        $instance->setContainer(($container->privates['.service_locator.nqgdEu8'] ?? $container->load('get_ServiceLocator_NqgdEu8Service'))->withContext('Oveleon\\ContaoCookiebar\\Controller\\ContentElement\\CookiebarOpenerController', $container));

        return $instance;
    }
}
