<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCodefogTags_Listener_TagManagerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'codefog_tags.listener.tag_manager' shared service.
     *
     * @return \Codefog\TagsBundle\EventListener\TagManagerListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/codefog/tags-bundle/src/EventListener/TagManagerListener.php';

        return $container->services['codefog_tags.listener.tag_manager'] = new \Codefog\TagsBundle\EventListener\TagManagerListener(($container->services['codefog_tags.manager_registry'] ?? $container->load('getCodefogTags_ManagerRegistryService')), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['contao.routing.scope_matcher'] ?? self::getContao_Routing_ScopeMatcherService($container)));
    }
}
