<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoryPermissionListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Codefog\NewsCategoriesBundle\EventListener\DataContainer\CategoryPermissionListener' shared autowired service.
     *
     * @return \Codefog\NewsCategoriesBundle\EventListener\DataContainer\CategoryPermissionListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/codefog/contao-news_categories/src/EventListener/DataContainer/CategoryPermissionListener.php';

        return $container->services['Codefog\\NewsCategoriesBundle\\EventListener\\DataContainer\\CategoryPermissionListener'] = new \Codefog\NewsCategoriesBundle\EventListener\DataContainer\CategoryPermissionListener(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['security.helper'] ?? self::getSecurity_HelperService($container)), ($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)));
    }
}
