<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContaoCookiebar_Listener_InsertTagsService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'contao_cookiebar.listener.insert_tags' shared service.
     *
     * @return \Oveleon\ContaoCookiebar\EventListener\InsertTagsListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/oveleon/contao-cookiebar/src/EventListener/InsertTagsListener.php';

        return $container->services['contao_cookiebar.listener.insert_tags'] = new \Oveleon\ContaoCookiebar\EventListener\InsertTagsListener(($container->services['contao.framework'] ?? self::getContao_FrameworkService($container)), ($container->privates['router.default'] ?? self::getRouter_DefaultService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
