<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContaoBundleCreatorService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Markocupic\ContaoBundleCreatorBundle\DataContainer\ContaoBundleCreator' shared autowired service.
     *
     * @return \Markocupic\ContaoBundleCreatorBundle\DataContainer\ContaoBundleCreator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/contao-bundle-creator-bundle/src/DataContainer/ContaoBundleCreator.php';
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/contao-bundle-creator-bundle/src/BundleMaker/BundleMaker.php';
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/contao-bundle-creator-bundle/src/BundleMaker/Storage/FileStorage.php';
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/contao-bundle-creator-bundle/src/BundleMaker/Storage/TagStorage.php';
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/contao-bundle-creator-bundle/src/BundleMaker/Message/Message.php';
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/zip-bundle/src/Zip/Zip.php';

        $a = ($container->services['contao.framework'] ?? self::getContao_FrameworkService($container));
        $b = ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack());

        return $container->services['Markocupic\\ContaoBundleCreatorBundle\\DataContainer\\ContaoBundleCreator'] = new \Markocupic\ContaoBundleCreatorBundle\DataContainer\ContaoBundleCreator(new \Markocupic\ContaoBundleCreatorBundle\BundleMaker\BundleMaker($a, $b, new \Markocupic\ContaoBundleCreatorBundle\BundleMaker\Storage\FileStorage(\dirname(__DIR__, 4)), new \Markocupic\ContaoBundleCreatorBundle\BundleMaker\Storage\TagStorage(), ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container)), new \Markocupic\ContaoBundleCreatorBundle\BundleMaker\Message\Message($a, $b), ($container->services['markocupic.zip_bundle.zip.zip'] ??= new \Markocupic\ZipBundle\Zip\Zip()), \dirname(__DIR__, 4)), $b, \dirname(__DIR__, 4));
    }
}
