<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContao_Fragment_Contao_ContentElement_GalleryCreatorNewsService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'contao.fragment._contao.content_element.gallery_creator_news' shared autowired service.
     *
     * @return \Markocupic\GalleryCreatorBundle\Controller\ContentElement\GalleryCreatorNewsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Fragment/FragmentOptionsAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Controller/AbstractFragmentController.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Controller/ContentElement/AbstractContentElementController.php';
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/gallery-creator-bundle/src/Controller/ContentElement/AbstractGalleryCreatorController.php';
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/gallery-creator-bundle/src/Controller/ContentElement/GalleryCreatorNewsController.php';

        $container->services['contao.fragment._contao.content_element.gallery_creator_news'] = $instance = new \Markocupic\GalleryCreatorBundle\Controller\ContentElement\GalleryCreatorNewsController(($container->services['Markocupic\\GalleryCreatorBundle\\Controller\\ContentElement\\DependencyAggregate'] ?? $container->load('getDependencyAggregateService')), ($container->services['twig'] ?? self::getTwigService($container)));

        $instance->setFragmentOptions(['type' => 'gallery_creator_news', 'category' => 'gallery_creator_elements', 'template' => 'content_element/gallery_creator_news', 'method' => NULL, 'renderer' => NULL, 'nestedFragments' => false, 'priority' => 0, 'debugController' => 'Markocupic\\GalleryCreatorBundle\\Controller\\ContentElement\\GalleryCreatorNewsController']);
        $instance->setContainer(($container->privates['.service_locator.6QgB1j.'] ?? $container->load('get_ServiceLocator_6QgB1j_Service'))->withContext('contao.fragment._contao.content_element.gallery_creator_news', $container));

        return $instance;
    }
}
