<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCodefogTags_Manager_Terminal42NodeService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'codefog_tags.manager.terminal42_node' shared service.
     *
     * @return \Codefog\TagsBundle\Manager\DefaultManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/codefog/tags-bundle/src/Manager/ManagerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/codefog/tags-bundle/src/Manager/DcaAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/codefog/tags-bundle/src/Manager/InsertTagsAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/codefog/tags-bundle/src/Manager/DefaultManager.php';
        include_once \dirname(__DIR__, 4).'/vendor/codefog/tags-bundle/src/Finder/TagFinder.php';
        include_once \dirname(__DIR__, 4).'/vendor/codefog/tags-bundle/src/Finder/SourceFinder.php';

        $container->services['codefog_tags.manager.terminal42_node'] = $instance = new \Codefog\TagsBundle\Manager\DefaultManager('terminal42_node', ['tl_node.tags']);

        $instance->setTagFinder(new \Codefog\TagsBundle\Finder\TagFinder());
        $instance->setSourcefinder(new \Codefog\TagsBundle\Finder\SourceFinder(($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)), ($container->services['Codefog\\HasteBundle\\DcaRelationsManager'] ?? $container->load('getDcaRelationsManagerService'))));

        return $instance;
    }
}
