<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCheckListingControllerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Diversworld\ContaoCheckBundle\Controller\FrontendModule\CheckListingController' shared autowired service.
     *
     * @return \Diversworld\ContaoCheckBundle\Controller\FrontendModule\CheckListingController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Fragment/FragmentOptionsAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Controller/AbstractFragmentController.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Controller/FrontendModule/AbstractFrontendModuleController.php';
        include_once \dirname(__DIR__, 4).'/vendor/diversworld/contao-check-bundle/src/Controller/FrontendModule/CheckListingController.php';

        $container->services['Diversworld\\ContaoCheckBundle\\Controller\\FrontendModule\\CheckListingController'] = $instance = new \Diversworld\ContaoCheckBundle\Controller\FrontendModule\CheckListingController();

        $instance->setContainer(($container->privates['.service_locator.3wBV1id'] ?? $container->load('get_ServiceLocator_3wBV1idService'))->withContext('Diversworld\\ContaoCheckBundle\\Controller\\FrontendModule\\CheckListingController', $container));

        return $instance;
    }
}
