<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConfigureFolderPageListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Terminal42\FolderpageBundle\EventListener\ConfigureFolderPageListener' shared autowired service.
     *
     * @return \Terminal42\FolderpageBundle\EventListener\ConfigureFolderPageListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-folderpage/src/EventListener/ConfigureFolderPageListener.php';

        return $container->services['Terminal42\\FolderpageBundle\\EventListener\\ConfigureFolderPageListener'] = new \Terminal42\FolderpageBundle\EventListener\ConfigureFolderPageListener(($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)));
    }
}
