<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContao_Fragment_Contao_FrontendModule_EventRegistrationCancelService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'contao.fragment._contao.frontend_module.event_registration_cancel' shared autowired service.
     *
     * @return \InspiredMinds\ContaoEventRegistration\Controller\FrontendModule\EventRegistrationCancelController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Fragment/FragmentOptionsAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Controller/AbstractFragmentController.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Controller/FrontendModule/AbstractFrontendModuleController.php';
        include_once \dirname(__DIR__, 4).'/vendor/inspiredminds/contao-event-registration/src/Controller/FrontendModule/EventRegistrationCancelController.php';
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-node/src/NodeManager.php';

        $container->services['contao.fragment._contao.frontend_module.event_registration_cancel'] = $instance = new \InspiredMinds\ContaoEventRegistration\Controller\FrontendModule\EventRegistrationCancelController(($container->privates['InspiredMinds\\ContaoEventRegistration\\EventRegistration'] ?? $container->load('getEventRegistrationService')), ($container->services['terminal42_node.manager'] ??= new \Terminal42\NodeBundle\NodeManager()), ($container->services['translator'] ?? self::getTranslatorService($container)), ($container->services['contao.string.simple_token_parser'] ?? $container->load('getContao_String_SimpleTokenParserService')), ($container->privates['Terminal42\\NotificationCenterBundle\\NotificationCenter'] ?? $container->load('getNotificationCenterService')), ($container->privates['InspiredMinds\\ContaoEventRegistration\\WaitingListChecker'] ?? $container->load('getWaitingListCheckerService')));

        $instance->setFragmentOptions(['type' => 'event_registration_cancel', 'category' => 'events', 'template' => 'mod_event_registration_cancel', 'debugController' => 'InspiredMinds\\ContaoEventRegistration\\Controller\\FrontendModule\\EventRegistrationCancelController']);
        $instance->setContainer(($container->privates['.service_locator..72JI_b'] ?? $container->load('get_ServiceLocator__72JIBService'))->withContext('contao.fragment._contao.frontend_module.event_registration_cancel', $container));

        return $instance;
    }
}
