<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCookiebarControllerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Oveleon\ContaoCookiebar\Controller\CookiebarController' shared autowired service.
     *
     * @return \Oveleon\ContaoCookiebar\Controller\CookiebarController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/oveleon/contao-cookiebar/src/Controller/CookiebarController.php';

        return $container->services['Oveleon\\ContaoCookiebar\\Controller\\CookiebarController'] = new \Oveleon\ContaoCookiebar\Controller\CookiebarController(($container->services['contao.framework'] ?? self::getContao_FrameworkService($container)), ($container->services['translator'] ?? self::getTranslatorService($container)));
    }
}
