<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContao_Fragment_Contao_FrontendModule_LeadsoptinService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'contao.fragment._contao.frontend_module.leadsoptin' shared autowired service.
     *
     * @return \Cgoit\LeadsOptinBundle\Controller\Module\LeadsOptInModule
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Fragment/FragmentOptionsAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Controller/AbstractFragmentController.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Controller/FrontendModule/AbstractFrontendModuleController.php';
        include_once \dirname(__DIR__, 4).'/vendor/cgoit/contao-leads-optin-bundle/src/Trait/TokenTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/cgoit/contao-leads-optin-bundle/src/Controller/Module/LeadsOptInModule.php';

        $container->services['contao.fragment._contao.frontend_module.leadsoptin'] = $instance = new \Cgoit\LeadsOptinBundle\Controller\Module\LeadsOptInModule(($container->privates['Terminal42\\NotificationCenterBundle\\NotificationCenter'] ?? $container->load('getNotificationCenterService')), ($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)), ($container->services['Codefog\\HasteBundle\\StringParser'] ?? $container->load('getStringParserService')));

        $instance->setFragmentOptions(['type' => 'leadsoptin', 'category' => 'leads', 'template' => 'mod_leads_optin', 'method' => NULL, 'renderer' => NULL, 'priority' => 0, 'debugController' => 'Cgoit\\LeadsOptinBundle\\Controller\\Module\\LeadsOptInModule']);
        $instance->setContainer(($container->privates['.service_locator.llMC0Xg'] ?? $container->load('get_ServiceLocator_LlMC0XgService'))->withContext('contao.fragment._contao.frontend_module.leadsoptin', $container));

        return $instance;
    }
}
