<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCodefogTags_ManagerRegistryService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'codefog_tags.manager_registry' shared service.
     *
     * @return \Codefog\TagsBundle\ManagerRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/codefog/tags-bundle/src/ManagerRegistry.php';

        $container->services['codefog_tags.manager_registry'] = $instance = new \Codefog\TagsBundle\ManagerRegistry();

        $instance->add(($container->services['codefog_tags.manager.terminal42_node'] ?? $container->load('getCodefogTags_Manager_Terminal42NodeService')), 'terminal42_node');

        return $instance;
    }
}
