<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCodefogTags_Listener_DataContainer_TagService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'codefog_tags.listener.data_container.tag' shared service.
     *
     * @return \Codefog\TagsBundle\EventListener\DataContainer\TagListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/codefog/tags-bundle/src/EventListener/DataContainer/TagListener.php';

        return $container->services['codefog_tags.listener.data_container.tag'] = new \Codefog\TagsBundle\EventListener\DataContainer\TagListener(($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)), ($container->services['codefog_tags.manager_registry'] ?? $container->load('getCodefogTags_ManagerRegistryService')), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
