<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContaoPdfformsbundle_Listener_InsertTagsService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'contao_pdfformsbundle.listener.insert_tags' shared autowired service.
     *
     * @return \Softleister\PdfformsBundle\EventListener\ReplaceInsertTagsListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/do-while/contao-pdfforms-bundle/src/EventListener/ReplaceInsertTagsListener.php';

        return $container->services['contao_pdfformsbundle.listener.insert_tags'] = new \Softleister\PdfformsBundle\EventListener\ReplaceInsertTagsListener(($container->services['contao.framework'] ?? self::getContao_FrameworkService($container)));
    }
}
