<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChildRecordCallbackListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'InspiredMinds\ContaoEventRegistration\EventListener\DataContainer\EventRegistration\ChildRecordCallbackListener' shared autowired service.
     *
     * @return \InspiredMinds\ContaoEventRegistration\EventListener\DataContainer\EventRegistration\ChildRecordCallbackListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/inspiredminds/contao-event-registration/src/EventListener/DataContainer/EventRegistration/ChildRecordCallbackListener.php';

        return $container->services['InspiredMinds\\ContaoEventRegistration\\EventListener\\DataContainer\\EventRegistration\\ChildRecordCallbackListener'] = new \InspiredMinds\ContaoEventRegistration\EventListener\DataContainer\EventRegistration\ChildRecordCallbackListener(($container->privates['InspiredMinds\\ContaoEventRegistration\\EventRegistration\\LabelBuilder'] ?? $container->load('getLabelBuilderService')), ($container->services['translator'] ?? self::getTranslatorService($container)));
    }
}
