<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDlstatsControllerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'BugBuster\DlstatsBundle\Controller\DlstatsController' shared autowired service.
     *
     * @return \BugBuster\DlstatsBundle\Controller\DlstatsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/bugbuster/contao-dlstats-bundle/src/Controller/DlstatsController.php';

        $container->services['BugBuster\\DlstatsBundle\\Controller\\DlstatsController'] = $instance = new \BugBuster\DlstatsBundle\Controller\DlstatsController();

        $instance->setContainer($container);

        return $instance;
    }
}
