<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDcaAuthorListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'HeimrichHannot\UtilsBundle\EventListener\DcaField\DcaAuthorListener' shared autowired service.
     *
     * @return \HeimrichHannot\UtilsBundle\EventListener\DcaField\DcaAuthorListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/heimrichhannot/contao-utils-bundle/src/EventListener/DcaField/AbstractDcaFieldListener.php';
        include_once \dirname(__DIR__, 4).'/vendor/heimrichhannot/contao-utils-bundle/src/EventListener/DcaField/DcaAuthorListener.php';

        return $container->services['HeimrichHannot\\UtilsBundle\\EventListener\\DcaField\\DcaAuthorListener'] = new \HeimrichHannot\UtilsBundle\EventListener\DcaField\DcaAuthorListener((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'contao.framework' => ['services', 'contao.framework', 'getContao_FrameworkService', false],
            'token_storage' => ['services', 'security.token_storage', 'getSecurity_TokenStorageService', false],
        ], [
            'contao.framework' => '?',
            'token_storage' => '?',
        ]))->withContext('HeimrichHannot\\UtilsBundle\\EventListener\\DcaField\\DcaAuthorListener', $container));
    }
}
