<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDateFormatterService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the private 'Terminal42\LeadsBundle\Export\Format\DateFormatter' shared autowired service.
     *
     * @return \Terminal42\LeadsBundle\Export\Format\DateFormatter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-leads/src/Export/Format/FormatterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-leads/src/Export/Format/DateFormatter.php';

        return $container->privates['Terminal42\\LeadsBundle\\Export\\Format\\DateFormatter'] = new \Terminal42\LeadsBundle\Export\Format\DateFormatter();
    }
}
