<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDcaUtilService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the private 'HeimrichHannot\UtilsBundle\Util\DcaUtil' shared autowired service.
     *
     * @return \HeimrichHannot\UtilsBundle\Util\DcaUtil
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/heimrichhannot/contao-utils-bundle/src/Util/DcaUtil.php';

        return $container->privates['HeimrichHannot\\UtilsBundle\\Util\\DcaUtil'] = new \HeimrichHannot\UtilsBundle\Util\DcaUtil(($container->services['contao.framework'] ?? self::getContao_FrameworkService($container)));
    }
}
