<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDatabaseUtilService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the private 'HeimrichHannot\UtilsBundle\Util\DatabaseUtil' shared autowired service.
     *
     * @return \HeimrichHannot\UtilsBundle\Util\DatabaseUtil
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/heimrichhannot/contao-utils-bundle/src/Util/DatabaseUtil.php';

        return $container->privates['HeimrichHannot\\UtilsBundle\\Util\\DatabaseUtil'] = new \HeimrichHannot\UtilsBundle\Util\DatabaseUtil();
    }
}
