<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDependencyAggregateService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Markocupic\GalleryCreatorBundle\Controller\ContentElement\DependencyAggregate' shared autowired service.
     *
     * @return \Markocupic\GalleryCreatorBundle\Controller\ContentElement\DependencyAggregate
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/gallery-creator-bundle/src/Controller/ContentElement/DependencyAggregate.php';

        return $container->services['Markocupic\\GalleryCreatorBundle\\Controller\\ContentElement\\DependencyAggregate'] = new \Markocupic\GalleryCreatorBundle\Controller\ContentElement\DependencyAggregate(($container->services['Markocupic\\GalleryCreatorBundle\\Util\\AlbumUtil'] ?? $container->load('getAlbumUtilService')), ($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)), ($container->services['contao.string.html_decoder'] ?? $container->load('getContao_String_HtmlDecoderService')), ($container->services['contao.insert_tag.parser'] ?? $container->load('getContao_InsertTag_ParserService')), ($container->services['Markocupic\\GalleryCreatorBundle\\Util\\MarkdownUtil'] ?? $container->load('getMarkdownUtilService')), ($container->services['Markocupic\\GalleryCreatorBundle\\Util\\PictureUtil'] ?? $container->load('getPictureUtilService')), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['contao.routing.response_context_accessor'] ?? $container->load('getContao_Routing_ResponseContextAccessorService')), ($container->services['contao.routing.scope_matcher'] ?? self::getContao_Routing_ScopeMatcherService($container)), ($container->services['Markocupic\\GalleryCreatorBundle\\Util\\SecurityUtil'] ?? $container->load('getSecurityUtilService')), ($container->services['contao.image.studio'] ?? $container->load('getContao_Image_StudioService')), \dirname(__DIR__, 4));
    }
}
