<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExportFieldOptionsListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Terminal42\LeadsBundle\EventListener\DataContainer\ExportFieldOptionsListener' shared autowired service.
     *
     * @return \Terminal42\LeadsBundle\EventListener\DataContainer\ExportFieldOptionsListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-leads/src/EventListener/DataContainer/ExportFieldOptionsListener.php';

        return $container->services['Terminal42\\LeadsBundle\\EventListener\\DataContainer\\ExportFieldOptionsListener'] = new \Terminal42\LeadsBundle\EventListener\DataContainer\ExportFieldOptionsListener(($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)), ($container->services['translator'] ?? self::getTranslatorService($container)));
    }
}
