<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEntityStorageFactoryService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the private 'Mvo\ContaoGroupWidget\Storage\EntityStorageFactory' shared service.
     *
     * @return \Mvo\ContaoGroupWidget\Storage\EntityStorageFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/mvo/contao-group-widget/src/Storage/StorageFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/mvo/contao-group-widget/src/Storage/EntityStorageFactory.php';

        return $container->privates['Mvo\\ContaoGroupWidget\\Storage\\EntityStorageFactory'] = new \Mvo\ContaoGroupWidget\Storage\EntityStorageFactory(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
