<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventRegistrationFormListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'InspiredMinds\ContaoEventRegistration\EventListener\EventRegistrationFormListener' shared autowired service.
     *
     * @return \InspiredMinds\ContaoEventRegistration\EventListener\EventRegistrationFormListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/inspiredminds/contao-event-registration/src/EventListener/EventRegistrationFormListener.php';

        return $container->services['InspiredMinds\\ContaoEventRegistration\\EventListener\\EventRegistrationFormListener'] = new \InspiredMinds\ContaoEventRegistration\EventListener\EventRegistrationFormListener(($container->privates['InspiredMinds\\ContaoEventRegistration\\EventRegistration'] ?? $container->load('getEventRegistrationService')), ($container->services['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)), ($container->services['translator'] ?? self::getTranslatorService($container)), ($container->privates['lock.default.factory'] ?? $container->load('getLock_Default_FactoryService')));
    }
}
