<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExportButtonCallbackListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'InspiredMinds\ContaoEventRegistration\EventListener\DataContainer\EventRegistration\ExportButtonCallbackListener' shared autowired service.
     *
     * @return \InspiredMinds\ContaoEventRegistration\EventListener\DataContainer\EventRegistration\ExportButtonCallbackListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/inspiredminds/contao-event-registration/src/EventListener/DataContainer/EventRegistration/ExportButtonCallbackListener.php';

        return $container->services['InspiredMinds\\ContaoEventRegistration\\EventListener\\DataContainer\\EventRegistration\\ExportButtonCallbackListener'] = new \InspiredMinds\ContaoEventRegistration\EventListener\DataContainer\EventRegistration\ExportButtonCallbackListener(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['router'] ?? self::getRouterService($container)));
    }
}
