<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventParseTemplateListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'InspiredMinds\ContaoEventRegistration\EventListener\EventParseTemplateListener' shared autowired service.
     *
     * @return \InspiredMinds\ContaoEventRegistration\EventListener\EventParseTemplateListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/inspiredminds/contao-event-registration/src/EventListener/EventParseTemplateListener.php';

        return $container->services['InspiredMinds\\ContaoEventRegistration\\EventListener\\EventParseTemplateListener'] = new \InspiredMinds\ContaoEventRegistration\EventListener\EventParseTemplateListener(($container->privates['InspiredMinds\\ContaoEventRegistration\\EventRegistration'] ?? $container->load('getEventRegistrationService')));
    }
}
