<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventRegistrationTokensListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the private 'InspiredMinds\ContaoEventRegistration\EventListener\NotificationCenter\EventRegistrationTokensListener' shared autowired service.
     *
     * @return \InspiredMinds\ContaoEventRegistration\EventListener\NotificationCenter\EventRegistrationTokensListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/inspiredminds/contao-event-registration/src/EventListener/NotificationCenter/EventRegistrationTokensListener.php';

        return $container->privates['InspiredMinds\\ContaoEventRegistration\\EventListener\\NotificationCenter\\EventRegistrationTokensListener'] = new \InspiredMinds\ContaoEventRegistration\EventListener\NotificationCenter\EventRegistrationTokensListener(($container->privates['Terminal42\\NotificationCenterBundle\\Token\\Definition\\Factory\\ChainTokenDefinitionFactory'] ?? $container->load('getChainTokenDefinitionFactoryService')), $container->parameters['contao_event_registration.tokens.supported_notifications']);
    }
}
