<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExportFormatOptionsListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Terminal42\LeadsBundle\EventListener\DataContainer\ExportFormatOptionsListener' shared autowired service.
     *
     * @return \Terminal42\LeadsBundle\EventListener\DataContainer\ExportFormatOptionsListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-leads/src/EventListener/DataContainer/ExportFormatOptionsListener.php';

        return $container->services['Terminal42\\LeadsBundle\\EventListener\\DataContainer\\ExportFormatOptionsListener'] = new \Terminal42\LeadsBundle\EventListener\DataContainer\ExportFormatOptionsListener(($container->privates['terminal42_leads.formatters'] ?? $container->load('getTerminal42Leads_FormattersService')), ($container->services['translator'] ?? self::getTranslatorService($container)));
    }
}
