<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormFieldService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Markocupic\ContaoAltchaAntispam\DataContainer\FormField' shared autowired service.
     *
     * @return \Markocupic\ContaoAltchaAntispam\DataContainer\FormField
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/contao-altcha-antispam/src/DataContainer/FormField.php';

        return $container->services['Markocupic\\ContaoAltchaAntispam\\DataContainer\\FormField'] = new \Markocupic\ContaoAltchaAntispam\DataContainer\FormField(($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)), ($container->services['contao.framework'] ?? self::getContao_FrameworkService($container)), ($container->services['security.authorization_checker'] ?? self::getSecurity_AuthorizationCheckerService($container)), ($container->services['translator'] ?? self::getTranslatorService($container)), '');
    }
}
