<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetAllEventsListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Pdir\MaeEventCategoriesBundle\EventListener\GetAllEventsListener' shared autowired service.
     *
     * @return \Pdir\MaeEventCategoriesBundle\EventListener\GetAllEventsListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/marebe1602/mae_event_categories/src/EventListener/GetAllEventsListener.php';

        return $container->services['Pdir\\MaeEventCategoriesBundle\\EventListener\\GetAllEventsListener'] = new \Pdir\MaeEventCategoriesBundle\EventListener\GetAllEventsListener();
    }
}
