<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGalleryCreatorAlbumsService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Markocupic\GalleryCreatorBundle\DataContainer\GalleryCreatorAlbums' shared autowired service.
     *
     * @return \Markocupic\GalleryCreatorBundle\DataContainer\GalleryCreatorAlbums
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/gallery-creator-bundle/src/DataContainer/GalleryCreatorAlbums.php';

        return $container->services['Markocupic\\GalleryCreatorBundle\\DataContainer\\GalleryCreatorAlbums'] = new \Markocupic\GalleryCreatorBundle\DataContainer\GalleryCreatorAlbums(($container->services['contao.framework'] ?? self::getContao_FrameworkService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['Markocupic\\GalleryCreatorBundle\\Util\\FileUtil'] ?? $container->load('getFileUtilService')), ($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)), ($container->services['security.helper'] ?? self::getSecurity_HelperService($container)), ($container->services['translator'] ?? self::getTranslatorService($container)), ($container->services['contao.image.factory'] ?? $container->load('getContao_Image_FactoryService')), ($container->services['twig'] ?? self::getTwigService($container)), ($container->services['Markocupic\\GalleryCreatorBundle\\Revise\\ReviseAlbumDatabase'] ?? $container->load('getReviseAlbumDatabaseService')), ($container->services['fos_http_cache.cache_manager'] ?? self::getFosHttpCache_CacheManagerService($container)), \dirname(__DIR__, 4), 'files/gallery_creator_albums', $container->parameters['markocupic_gallery_creator.valid_extensions']);
    }
}
