<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHuh_Ajax_ActionService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'huh.ajax.action' shared service.
     *
     * @return \HeimrichHannot\AjaxBundle\Manager\AjaxActionManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/heimrichhannot/contao-ajax-bundle/src/Manager/AjaxActionManager.php';

        return $container->services['huh.ajax.action'] = new \HeimrichHannot\AjaxBundle\Manager\AjaxActionManager();
    }
}
