<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHookListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'ContaoThemesNet\MateThemeBundle\EventListener\HookListener' shared autowired service.
     *
     * @return \ContaoThemesNet\MateThemeBundle\EventListener\HookListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao-themes-net/mate-theme-bundle/src/EventListener/HookListener.php';

        return $container->services['ContaoThemesNet\\MateThemeBundle\\EventListener\\HookListener'] = new \ContaoThemesNet\MateThemeBundle\EventListener\HookListener();
    }
}
