<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImageCopyrightListControllerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Tastaturberuf\ContaoImageCopyrightBundle\Controller\ImageCopyrightListController' shared autowired service.
     *
     * @return \Tastaturberuf\ContaoImageCopyrightBundle\Controller\ImageCopyrightListController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Fragment/FragmentOptionsAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Controller/AbstractFragmentController.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Controller/FrontendModule/AbstractFrontendModuleController.php';
        include_once \dirname(__DIR__, 4).'/vendor/tastaturberuf/contao-image-copyright-bundle/Controller/ImageCopyrightListController.php';

        $container->services['Tastaturberuf\\ContaoImageCopyrightBundle\\Controller\\ImageCopyrightListController'] = $instance = new \Tastaturberuf\ContaoImageCopyrightBundle\Controller\ImageCopyrightListController(($container->services['contao.image.factory'] ?? $container->load('getContao_Image_FactoryService')), \dirname(__DIR__, 4), $container->parameters['contao.image.valid_extensions']);

        $instance->setContainer(($container->privates['.service_locator.nqgdEu8'] ?? $container->load('get_ServiceLocator_NqgdEu8Service'))->withContext('Tastaturberuf\\ContaoImageCopyrightBundle\\Controller\\ImageCopyrightListController', $container));

        return $instance;
    }
}
