<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInsertTagsListener2Service extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Codefog\NewsCategoriesBundle\EventListener\InsertTagsListener' shared autowired service.
     *
     * @return \Codefog\NewsCategoriesBundle\EventListener\InsertTagsListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/codefog/contao-news_categories/src/EventListener/InsertTagsListener.php';

        return $container->services['Codefog\\NewsCategoriesBundle\\EventListener\\InsertTagsListener'] = new \Codefog\NewsCategoriesBundle\EventListener\InsertTagsListener(($container->services['contao.framework'] ?? self::getContao_FrameworkService($container)), ($container->services['Codefog\\NewsCategoriesBundle\\NewsCategoriesManager'] ?? $container->load('getNewsCategoriesManagerService')));
    }
}
