<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImportValidatorService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Markocupic\ImportFromCsvBundle\Import\Field\ImportValidator' shared autowired service.
     *
     * @return \Markocupic\ImportFromCsvBundle\Import\Field\ImportValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/import-from-csv-bundle/src/Import/Field/ImportValidator.php';

        $a = ($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container));

        if (isset($container->services['Markocupic\\ImportFromCsvBundle\\Import\\Field\\ImportValidator'])) {
            return $container->services['Markocupic\\ImportFromCsvBundle\\Import\\Field\\ImportValidator'];
        }

        return $container->services['Markocupic\\ImportFromCsvBundle\\Import\\Field\\ImportValidator'] = new \Markocupic\ImportFromCsvBundle\Import\Field\ImportValidator(($container->services['contao.framework'] ?? self::getContao_FrameworkService($container)), ($container->services['translator'] ?? self::getTranslatorService($container)), $a);
    }
}
