<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImportFromCsvHookExampleService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Markocupic\ImportFromCsvBundle\EventListener\ContaoHooks\ImportFromCsvHookExample' shared autowired service.
     *
     * @return \Markocupic\ImportFromCsvBundle\EventListener\ContaoHooks\ImportFromCsvHookExample
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/import-from-csv-bundle/src/EventListener/ContaoHooks/ImportFromCsvHookExample.php';

        return $container->services['Markocupic\\ImportFromCsvBundle\\EventListener\\ContaoHooks\\ImportFromCsvHookExample'] = new \Markocupic\ImportFromCsvBundle\EventListener\ContaoHooks\ImportFromCsvHookExample();
    }
}
