<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInitializeSystemListener2Service extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'HeimrichHannot\MultiColumnEditorBundle\EventListener\Contao\InitializeSystemListener' shared autowired service.
     *
     * @return \HeimrichHannot\MultiColumnEditorBundle\EventListener\Contao\InitializeSystemListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/heimrichhannot/contao-multi-column-editor-bundle/src/EventListener/Contao/InitializeSystemListener.php';

        return $container->services['HeimrichHannot\\MultiColumnEditorBundle\\EventListener\\Contao\\InitializeSystemListener'] = new \HeimrichHannot\MultiColumnEditorBundle\EventListener\Contao\InitializeSystemListener(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['contao.routing.scope_matcher'] ?? self::getContao_Routing_ScopeMatcherService($container)));
    }
}
