<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImportFromCsvHelperService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Markocupic\ImportFromCsvBundle\Import\ImportFromCsvHelper' shared autowired service.
     *
     * @return \Markocupic\ImportFromCsvBundle\Import\ImportFromCsvHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/import-from-csv-bundle/src/Import/ImportFromCsvHelper.php';

        $a = ($container->services['Markocupic\\ImportFromCsvBundle\\Import\\ImportFromCsv'] ?? $container->load('getImportFromCsv2Service'));

        if (isset($container->services['Markocupic\\ImportFromCsvBundle\\Import\\ImportFromCsvHelper'])) {
            return $container->services['Markocupic\\ImportFromCsvBundle\\Import\\ImportFromCsvHelper'];
        }

        return $container->services['Markocupic\\ImportFromCsvBundle\\Import\\ImportFromCsvHelper'] = new \Markocupic\ImportFromCsvBundle\Import\ImportFromCsvHelper(($container->services['contao.framework'] ?? self::getContao_FrameworkService($container)), $a, \dirname(__DIR__, 4));
    }
}
