<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImportAjaxControllerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Markocupic\ImportFromCsvBundle\Contao\Controller\ImportAjaxController' shared autowired service.
     *
     * @return \Markocupic\ImportFromCsvBundle\Contao\Controller\ImportAjaxController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/import-from-csv-bundle/src/Contao/Controller/ImportAjaxController.php';

        $container->services['Markocupic\\ImportFromCsvBundle\\Contao\\Controller\\ImportAjaxController'] = $instance = new \Markocupic\ImportFromCsvBundle\Contao\Controller\ImportAjaxController(($container->services['Markocupic\\ImportFromCsvBundle\\Import\\ImportFromCsvHelper'] ?? $container->load('getImportFromCsvHelperService')), ($container->services['contao.framework'] ?? self::getContao_FrameworkService($container)), ($container->services['contao.csrf.token_manager'] ?? self::getContao_Csrf_TokenManagerService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['Markocupic\\ImportFromCsvBundle\\Logger\\ImportLogger'] ?? $container->load('getImportLoggerService')), 'contao_csrf_token');

        $instance->setContainer($container);

        return $instance;
    }
}
