<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInsertTagsListener5Service extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Terminal42\PageimageBundle\EventListener\InsertTagsListener' shared service.
     *
     * @return \Terminal42\PageimageBundle\EventListener\InsertTagsListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-pageimage/src/EventListener/InsertTagsListener.php';
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-pageimage/src/PageimageHelper.php';

        return $container->services['Terminal42\\PageimageBundle\\EventListener\\InsertTagsListener'] = new \Terminal42\PageimageBundle\EventListener\InsertTagsListener(($container->privates['Terminal42\\PageimageBundle\\PageimageHelper'] ??= new \Terminal42\PageimageBundle\PageimageHelper()));
    }
}
