<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInitializeSystemListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'HeimrichHannot\AjaxBundle\EventListener\Contao\InitializeSystemListener' shared autowired service.
     *
     * @return \HeimrichHannot\AjaxBundle\EventListener\Contao\InitializeSystemListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/heimrichhannot/contao-ajax-bundle/src/EventListener/Contao/InitializeSystemListener.php';

        return $container->services['HeimrichHannot\\AjaxBundle\\EventListener\\Contao\\InitializeSystemListener'] = new \HeimrichHannot\AjaxBundle\EventListener\Contao\InitializeSystemListener(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['contao.routing.scope_matcher'] ?? self::getContao_Routing_ScopeMatcherService($container)), ($container->privates['security.csrf.token_manager'] ?? $container->load('getSecurity_Csrf_TokenManagerService')), ($container->privates['parameter_bag'] ??= new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container)), ($container->services['HeimrichHannot\\AjaxBundle\\Manager\\AjaxManager'] ?? $container->load('getAjaxManagerService')));
    }
}
