<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImportFromCsv2Service extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Markocupic\ImportFromCsvBundle\Import\ImportFromCsv' shared autowired service.
     *
     * @return \Markocupic\ImportFromCsvBundle\Import\ImportFromCsv
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/import-from-csv-bundle/src/Import/ImportFromCsv.php';

        $a = ($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container));

        if (isset($container->services['Markocupic\\ImportFromCsvBundle\\Import\\ImportFromCsv'])) {
            return $container->services['Markocupic\\ImportFromCsvBundle\\Import\\ImportFromCsv'];
        }
        $b = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->services['Markocupic\\ImportFromCsvBundle\\Import\\ImportFromCsv'])) {
            return $container->services['Markocupic\\ImportFromCsvBundle\\Import\\ImportFromCsv'];
        }
        $c = ($container->services['Markocupic\\ImportFromCsvBundle\\Import\\Field\\ImportValidator'] ?? $container->load('getImportValidatorService'));

        if (isset($container->services['Markocupic\\ImportFromCsvBundle\\Import\\ImportFromCsv'])) {
            return $container->services['Markocupic\\ImportFromCsvBundle\\Import\\ImportFromCsv'];
        }

        return $container->services['Markocupic\\ImportFromCsvBundle\\Import\\ImportFromCsv'] = new \Markocupic\ImportFromCsvBundle\Import\ImportFromCsv(($container->services['contao.framework'] ?? self::getContao_FrameworkService($container)), $a, $b, ($container->services['Markocupic\\ImportFromCsvBundle\\Import\\Field\\Formatter'] ?? $container->load('getFormatter2Service')), ($container->services['Markocupic\\ImportFromCsvBundle\\Logger\\ImportLogger'] ?? $container->load('getImportLoggerService')), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), $c, \dirname(__DIR__, 4));
    }
}
