<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImportFromCsvModelService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Markocupic\ImportFromCsvBundle\Model\ImportFromCsvModel' shared autowired service.
     *
     * @return \Markocupic\ImportFromCsvBundle\Model\ImportFromCsvModel
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/contao/library/Contao/Model.php';
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/import-from-csv-bundle/src/Model/ImportFromCsvModel.php';

        return $container->services['Markocupic\\ImportFromCsvBundle\\Model\\ImportFromCsvModel'] = new \Markocupic\ImportFromCsvBundle\Model\ImportFromCsvModel();
    }
}
