<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImportFromCsvService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Markocupic\ImportFromCsvBundle\DataContainer\ImportFromCsv' shared autowired service.
     *
     * @return \Markocupic\ImportFromCsvBundle\DataContainer\ImportFromCsv
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/import-from-csv-bundle/src/DataContainer/ImportFromCsv.php';

        return $container->services['Markocupic\\ImportFromCsvBundle\\DataContainer\\ImportFromCsv'] = new \Markocupic\ImportFromCsvBundle\DataContainer\ImportFromCsv(($container->services['contao.framework'] ?? self::getContao_FrameworkService($container)), ($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)), ($container->services['translator'] ?? self::getTranslatorService($container)), ($container->services['twig'] ?? self::getTwigService($container)), \dirname(__DIR__, 4));
    }
}
