<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMarkdownUtilService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Markocupic\GalleryCreatorBundle\Util\MarkdownUtil' shared autowired service.
     *
     * @return \Markocupic\GalleryCreatorBundle\Util\MarkdownUtil
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/gallery-creator-bundle/src/Util/MarkdownUtil.php';

        return $container->services['Markocupic\\GalleryCreatorBundle\\Util\\MarkdownUtil'] = new \Markocupic\GalleryCreatorBundle\Util\MarkdownUtil(($container->services['contao.framework'] ?? self::getContao_FrameworkService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['contao.insert_tag.parser'] ?? $container->load('getContao_InsertTag_ParserService')));
    }
}
