<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMarkocupic_ImportFromCsv_Session_Attribute_ArrayAttributeBagService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'markocupic.import_from_csv.session.attribute.array_attribute_bag' shared autowired service.
     *
     * @return \Markocupic\ImportFromCsvBundle\Session\Attribute\ArrayAttributeBag
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-foundation/Session/SessionBagInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-foundation/Session/Attribute/AttributeBagInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-foundation/Session/Attribute/AttributeBag.php';
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/import-from-csv-bundle/src/Session/Attribute/ArrayAttributeBag.php';

        $container->services['markocupic.import_from_csv.session.attribute.array_attribute_bag'] = $instance = new \Markocupic\ImportFromCsvBundle\Session\Attribute\ArrayAttributeBag('_markocupic_import_from_csv_attributes');

        $instance->setName('markocupic_import_from_csv');

        return $instance;
    }
}
