<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getModuleCallbacksService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Cgoit\CalendarExtendedBundle\EventListener\DataContainer\ModuleCallbacks' shared autowired service.
     *
     * @return \Cgoit\CalendarExtendedBundle\EventListener\DataContainer\ModuleCallbacks
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/contao/classes/Backend.php';
        include_once \dirname(__DIR__, 4).'/vendor/cgoit/calendar-extended-bundle/src/EventListener/DataContainer/ModuleCallbacks.php';

        return $container->services['Cgoit\\CalendarExtendedBundle\\EventListener\\DataContainer\\ModuleCallbacks'] = new \Cgoit\CalendarExtendedBundle\EventListener\DataContainer\ModuleCallbacks($container->parameters['cgoit_calendar_extended.filter_fields']);
    }
}
