<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMpFormsManagerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Markocupic\ContaoAltchaAntispam\Storage\MpFormsManager' shared autowired service.
     *
     * @return \Markocupic\ContaoAltchaAntispam\Storage\MpFormsManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/contao-altcha-antispam/src/Storage/MpFormsManager.php';

        return $container->services['Markocupic\\ContaoAltchaAntispam\\Storage\\MpFormsManager'] = new \Markocupic\ContaoAltchaAntispam\Storage\MpFormsManager(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
