<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMarkocupicGalleryCreatorBundleService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Markocupic\GalleryCreatorBundle\MarkocupicGalleryCreatorBundle' shared autowired service.
     *
     * @return \Markocupic\GalleryCreatorBundle\MarkocupicGalleryCreatorBundle
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Bundle/BundleInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Bundle/Bundle.php';
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/gallery-creator-bundle/src/MarkocupicGalleryCreatorBundle.php';

        return $container->services['Markocupic\\GalleryCreatorBundle\\MarkocupicGalleryCreatorBundle'] = new \Markocupic\GalleryCreatorBundle\MarkocupicGalleryCreatorBundle();
    }
}
