<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMyCustomControllerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Diversworld\ContaoCheckBundle\Controller\MyCustomController' shared autowired service.
     *
     * @return \Diversworld\ContaoCheckBundle\Controller\MyCustomController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/diversworld/contao-check-bundle/src/Controller/MyCustomController.php';

        $container->services['Diversworld\\ContaoCheckBundle\\Controller\\MyCustomController'] = $instance = new \Diversworld\ContaoCheckBundle\Controller\MyCustomController(($container->services['twig'] ?? self::getTwigService($container)));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('Diversworld\\ContaoCheckBundle\\Controller\\MyCustomController', $container));

        return $instance;
    }
}
