<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getModuleService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Cgoit\LeadsOptinBundle\EventListener\DataContainer\Module' shared autowired service.
     *
     * @return \Cgoit\LeadsOptinBundle\EventListener\DataContainer\Module
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/cgoit/contao-leads-optin-bundle/src/EventListener/DataContainer/Module.php';

        return $container->services['Cgoit\\LeadsOptinBundle\\EventListener\\DataContainer\\Module'] = new \Cgoit\LeadsOptinBundle\EventListener\DataContainer\Module(($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)));
    }
}
