<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewsCategoriesVoterService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the private 'Codefog\NewsCategoriesBundle\Security\Voter\DataContainer\NewsCategoriesVoter' shared autowired service.
     *
     * @return \Codefog\NewsCategoriesBundle\Security\Voter\DataContainer\NewsCategoriesVoter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/codefog/contao-news_categories/src/Security/Voter/DataContainer/NewsCategoriesVoter.php';

        $a = ($container->services['security.helper'] ?? self::getSecurity_HelperService($container));

        if (isset($container->privates['Codefog\\NewsCategoriesBundle\\Security\\Voter\\DataContainer\\NewsCategoriesVoter'])) {
            return $container->privates['Codefog\\NewsCategoriesBundle\\Security\\Voter\\DataContainer\\NewsCategoriesVoter'];
        }

        return $container->privates['Codefog\\NewsCategoriesBundle\\Security\\Voter\\DataContainer\\NewsCategoriesVoter'] = new \Codefog\NewsCategoriesBundle\Security\Voter\DataContainer\NewsCategoriesVoter($a, ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
