<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNumero2ProperFilenames_Listener_DataContainer_FilesService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'numero2_proper_filenames.listener.data_container.files' shared service.
     *
     * @return \numero2\ProperFilenamesBundle\EventListener\DataContainer\FilesListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/numero2/contao-proper-filenames/src/EventListener/DataContainer/FilesListener.php';

        return $container->services['numero2_proper_filenames.listener.data_container.files'] = new \numero2\ProperFilenamesBundle\EventListener\DataContainer\FilesListener();
    }
}
