<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNumero2ProperFilenames_Command_CleanFilesService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the private 'numero2_proper_filenames.command.clean_files' shared service.
     *
     * @return \numero2\ProperFilenamesBundle\Command\CleanFilesCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Framework/FrameworkAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Framework/FrameworkAwareTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/numero2/contao-proper-filenames/src/Command/CleanFilesCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/filesystem/Filesystem.php';

        $container->privates['numero2_proper_filenames.command.clean_files'] = $instance = new \numero2\ProperFilenamesBundle\Command\CleanFilesCommand(\dirname(__DIR__, 4), 'files', ($container->privates['filesystem'] ??= new \Symfony\Component\Filesystem\Filesystem()), ($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)));

        $instance->setFramework(($container->services['contao.framework'] ?? self::getContao_FrameworkService($container)));
        $instance->setName('contao:proper-filenames:sanitize');
        $instance->setDescription('Sanitizes the file and folder names of the given path inside contao files folder.');

        return $instance;
    }
}
