<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewsCriteriaBuilderService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Codefog\NewsCategoriesBundle\Criteria\NewsCriteriaBuilder' shared autowired service.
     *
     * @return \Codefog\NewsCategoriesBundle\Criteria\NewsCriteriaBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/codefog/contao-news_categories/src/Criteria/NewsCriteriaBuilder.php';

        return $container->services['Codefog\\NewsCategoriesBundle\\Criteria\\NewsCriteriaBuilder'] = new \Codefog\NewsCategoriesBundle\Criteria\NewsCriteriaBuilder(($container->services['contao.framework'] ?? self::getContao_FrameworkService($container)), ($container->services['contao.security.token_checker'] ?? self::getContao_Security_TokenCheckerService($container)), ($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)), ($container->services['Codefog\\NewsCategoriesBundle\\NewsCategoriesManager'] ?? $container->load('getNewsCategoriesManagerService')));
    }
}
