<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParseBackendTemplateService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Markocupic\GalleryCreatorBundle\EventListener\ContaoHook\ParseBackendTemplate' shared autowired service.
     *
     * @return \Markocupic\GalleryCreatorBundle\EventListener\ContaoHook\ParseBackendTemplate
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/gallery-creator-bundle/src/EventListener/ContaoHook/ParseBackendTemplate.php';

        return $container->services['Markocupic\\GalleryCreatorBundle\\EventListener\\ContaoHook\\ParseBackendTemplate'] = new \Markocupic\GalleryCreatorBundle\EventListener\ContaoHook\ParseBackendTemplate(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['contao.routing.scope_matcher'] ?? self::getContao_Routing_ScopeMatcherService($container)));
    }
}
