<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProcessFormDataListener2Service extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Markocupic\ContaoAltchaAntispam\EventListener\ProcessFormDataListener' shared autowired service.
     *
     * @return \Markocupic\ContaoAltchaAntispam\EventListener\ProcessFormDataListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/contao-altcha-antispam/src/EventListener/ProcessFormDataListener.php';

        return $container->services['Markocupic\\ContaoAltchaAntispam\\EventListener\\ProcessFormDataListener'] = new \Markocupic\ContaoAltchaAntispam\EventListener\ProcessFormDataListener(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), NULL);
    }
}
