<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrepareFormDataListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Cgoit\FormFillPdfBundle\EventListener\PrepareFormDataListener' shared autowired service.
     *
     * @return \Cgoit\FormFillPdfBundle\EventListener\PrepareFormDataListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/cgoit/contao-form-fill-pdf-bundle/src/EventListener/PrepareFormDataListener.php';

        return $container->services['Cgoit\\FormFillPdfBundle\\EventListener\\PrepareFormDataListener'] = new \Cgoit\FormFillPdfBundle\EventListener\PrepareFormDataListener(\dirname(__DIR__, 4), ($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)), ($container->services['Codefog\\HasteBundle\\StringParser'] ?? $container->load('getStringParserService')), ($container->services['contao.insert_tag.parser'] ?? $container->load('getContao_InsertTag_ParserService')), NULL);
    }
}
