<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPluginService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Markocupic\GalleryCreatorBundle\ContaoManager\Plugin' shared autowired service.
     *
     * @return \Markocupic\GalleryCreatorBundle\ContaoManager\Plugin
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao/manager-plugin/src/Bundle/BundlePluginInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/manager-plugin/src/Routing/RoutingPluginInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/gallery-creator-bundle/src/ContaoManager/Plugin.php';

        return $container->services['Markocupic\\GalleryCreatorBundle\\ContaoManager\\Plugin'] = new \Markocupic\GalleryCreatorBundle\ContaoManager\Plugin();
    }
}
