<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParseFrontendTemplateHookService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Cgoit\CalendarExtendedBundle\Hook\ParseFrontendTemplateHook' shared autowired service.
     *
     * @return \Cgoit\CalendarExtendedBundle\Hook\ParseFrontendTemplateHook
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/cgoit/calendar-extended-bundle/src/Hook/ParseFrontendTemplateHook.php';

        return $container->services['Cgoit\\CalendarExtendedBundle\\Hook\\ParseFrontendTemplateHook'] = new \Cgoit\CalendarExtendedBundle\Hook\ParseFrontendTemplateHook();
    }
}
