<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPhpSpreadsheetExporterService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the private 'Cgoit\LeadsOptinBundle\Exporter\PhpSpreadsheetExporter' shared autowired service.
     *
     * @return \Cgoit\LeadsOptinBundle\Exporter\PhpSpreadsheetExporter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-leads/src/Export/ExporterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-leads/src/Export/AbstractExporter.php';
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-leads/src/Export/PhpSpreadsheetExporter.php';
        include_once \dirname(__DIR__, 4).'/vendor/cgoit/contao-leads-optin-bundle/src/Exporter/ExporterTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/cgoit/contao-leads-optin-bundle/src/Exporter/PhpSpreadsheetExporter.php';

        return $container->privates['Cgoit\\LeadsOptinBundle\\Exporter\\PhpSpreadsheetExporter'] = new \Cgoit\LeadsOptinBundle\Exporter\PhpSpreadsheetExporter(\dirname(__DIR__, 4), ($container->privates['terminal42_leads.formatters'] ?? $container->load('getTerminal42Leads_FormattersService')), ($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)), ($container->services['translator'] ?? self::getTranslatorService($container)), ($container->services['Codefog\\HasteBundle\\StringParser'] ?? $container->load('getStringParserService')), ($container->privates['terminal42_leads.expression_language'] ?? $container->load('getTerminal42Leads_ExpressionLanguageService')));
    }
}
