<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParseTemplateListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Markocupic\BackendPasswordRecoveryBundle\EventListener\Contao\ParseTemplateListener' shared autowired service.
     *
     * @return \Markocupic\BackendPasswordRecoveryBundle\EventListener\Contao\ParseTemplateListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/backend-password-recovery-bundle/src/EventListener/Contao/ParseTemplateListener.php';
        include_once \dirname(__DIR__, 4).'/vendor/code4nix/uri-signer/src/UriSigner.php';

        return $container->services['Markocupic\\BackendPasswordRecoveryBundle\\EventListener\\Contao\\ParseTemplateListener'] = new \Markocupic\BackendPasswordRecoveryBundle\EventListener\Contao\ParseTemplateListener(($container->services['twig'] ?? self::getTwigService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['router'] ?? self::getRouterService($container)), ($container->services['contao.routing.scope_matcher'] ?? self::getContao_Routing_ScopeMatcherService($container)), ($container->services['translator'] ?? self::getTranslatorService($container)), ($container->services['code4nix_uri_signer.uri_signer'] ??= new \Code4Nix\UriSigner\UriSigner($container->getEnv('APP_SECRET'), '_hash', 3600)), true, 600);
    }
}
