<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResetVerifyControllerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Markocupic\BackendPasswordRecoveryBundle\Controller\ResetVerifyController' shared autowired service.
     *
     * @return \Markocupic\BackendPasswordRecoveryBundle\Controller\ResetVerifyController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/backend-password-recovery-bundle/src/Controller/ResetVerifyController.php';

        $container->services['Markocupic\\BackendPasswordRecoveryBundle\\Controller\\ResetVerifyController'] = $instance = new \Markocupic\BackendPasswordRecoveryBundle\Controller\ResetVerifyController();

        $instance->setContainer(($container->privates['.service_locator.HuDo1n.'] ?? $container->load('get_ServiceLocator_HuDo1n_Service'))->withContext('Markocupic\\BackendPasswordRecoveryBundle\\Controller\\ResetVerifyController', $container));

        return $instance;
    }
}
