<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRoutingUtilService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the private 'HeimrichHannot\UtilsBundle\Util\RoutingUtil' shared autowired service.
     *
     * @return \HeimrichHannot\UtilsBundle\Util\RoutingUtil
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/heimrichhannot/contao-utils-bundle/src/Util/RoutingUtil.php';

        $a = ($container->services['router'] ?? self::getRouterService($container));

        if (isset($container->privates['HeimrichHannot\\UtilsBundle\\Util\\RoutingUtil'])) {
            return $container->privates['HeimrichHannot\\UtilsBundle\\Util\\RoutingUtil'];
        }

        return $container->privates['HeimrichHannot\\UtilsBundle\\Util\\RoutingUtil'] = new \HeimrichHannot\UtilsBundle\Util\RoutingUtil(($container->services['contao.csrf.token_manager'] ?? self::getContao_Csrf_TokenManagerService($container)), $a, 'contao_csrf_token', ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
