<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReaderModuleOptionsListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Cgoit\CmaceBundle\EventListener\DataContainer\ReaderModuleOptionsListener' shared autowired service.
     *
     * @return \Cgoit\CmaceBundle\EventListener\DataContainer\ReaderModuleOptionsListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/cgoit/contao-cmace-bundle/src/EventListener/DataContainer/ReaderModuleOptionsListener.php';

        return $container->services['Cgoit\\CmaceBundle\\EventListener\\DataContainer\\ReaderModuleOptionsListener'] = new \Cgoit\CmaceBundle\EventListener\DataContainer\ReaderModuleOptionsListener(($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)));
    }
}
