<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRenderBackendAppControllerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Markocupic\ImportFromCsvBundle\Contao\Controller\RenderBackendAppController' shared autowired service.
     *
     * @return \Markocupic\ImportFromCsvBundle\Contao\Controller\RenderBackendAppController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/markocupic/import-from-csv-bundle/src/Contao/Controller/RenderBackendAppController.php';

        return $container->services['Markocupic\\ImportFromCsvBundle\\Contao\\Controller\\RenderBackendAppController'] = new \Markocupic\ImportFromCsvBundle\Contao\Controller\RenderBackendAppController(($container->services['contao.csrf.token_manager'] ?? self::getContao_Csrf_TokenManagerService($container)), ($container->services['contao.framework'] ?? self::getContao_FrameworkService($container)), ($container->services['Markocupic\\ImportFromCsvBundle\\Import\\ImportFromCsvHelper'] ?? $container->load('getImportFromCsvHelperService')), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['router'] ?? self::getRouterService($container)), ($container->services['twig'] ?? self::getTwigService($container)));
    }
}
