<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegistrationFormOptionsCallbackListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'InspiredMinds\ContaoEventRegistration\EventListener\DataContainer\CalendarEvents\RegistrationFormOptionsCallbackListener' shared autowired service.
     *
     * @return \InspiredMinds\ContaoEventRegistration\EventListener\DataContainer\CalendarEvents\RegistrationFormOptionsCallbackListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/inspiredminds/contao-event-registration/src/EventListener/DataContainer/CalendarEvents/RegistrationFormOptionsCallbackListener.php';

        return $container->services['InspiredMinds\\ContaoEventRegistration\\EventListener\\DataContainer\\CalendarEvents\\RegistrationFormOptionsCallbackListener'] = new \InspiredMinds\ContaoEventRegistration\EventListener\DataContainer\CalendarEvents\RegistrationFormOptionsCallbackListener(($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)), ($container->services['security.authorization_checker'] ?? self::getSecurity_AuthorizationCheckerService($container)));
    }
}
