<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSettingSlugOptionsListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Codefog\NewsCategoriesBundle\EventListener\DataContainer\SettingSlugOptionsListener' shared autowired service.
     *
     * @return \Codefog\NewsCategoriesBundle\EventListener\DataContainer\SettingSlugOptionsListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/codefog/contao-news_categories/src/EventListener/DataContainer/SettingSlugOptionsListener.php';

        return $container->services['Codefog\\NewsCategoriesBundle\\EventListener\\DataContainer\\SettingSlugOptionsListener'] = new \Codefog\NewsCategoriesBundle\EventListener\DataContainer\SettingSlugOptionsListener(($container->services['contao.slug.valid_characters'] ?? $container->load('getContao_Slug_ValidCharactersService')));
    }
}
