<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScriptUtilsService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Oveleon\ContaoCookiebar\Utils\ScriptUtils' shared autowired service.
     *
     * @return \Oveleon\ContaoCookiebar\Utils\ScriptUtils
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/oveleon/contao-cookiebar/src/Utils/ScriptUtils.php';

        return $container->services['Oveleon\\ContaoCookiebar\\Utils\\ScriptUtils'] = new \Oveleon\ContaoCookiebar\Utils\ScriptUtils();
    }
}
