<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSendNewsletterListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Terminal42\NewsNewsletterBundle\EventListener\SendNewsletterListener' shared autowired service.
     *
     * @return \Terminal42\NewsNewsletterBundle\EventListener\SendNewsletterListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-news_newsletter/src/EventListener/SendNewsletterListener.php';

        return $container->services['Terminal42\\NewsNewsletterBundle\\EventListener\\SendNewsletterListener'] = new \Terminal42\NewsNewsletterBundle\EventListener\SendNewsletterListener(($container->privates['Terminal42\\NotificationCenterBundle\\NotificationCenter'] ?? $container->load('getNotificationCenterService')), ($container->services['Codefog\\HasteBundle\\Formatter'] ?? $container->load('getFormatterService')));
    }
}
