<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTemplateListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Codefog\NewsCategoriesBundle\EventListener\TemplateListener' shared autowired service.
     *
     * @return \Codefog\NewsCategoriesBundle\EventListener\TemplateListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/codefog/contao-news_categories/src/EventListener/TemplateListener.php';

        return $container->services['Codefog\\NewsCategoriesBundle\\EventListener\\TemplateListener'] = new \Codefog\NewsCategoriesBundle\EventListener\TemplateListener(($container->services['contao.framework'] ?? self::getContao_FrameworkService($container)), ($container->services['Codefog\\NewsCategoriesBundle\\NewsCategoriesManager'] ?? $container->load('getNewsCategoriesManagerService')), ($container->services['contao.image.studio'] ?? $container->load('getContao_Image_StudioService')));
    }
}
