<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTerminal42Node_Listener_DataContainerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'terminal42_node.listener.data_container' shared service.
     *
     * @return \Terminal42\NodeBundle\EventListener\DataContainerListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-node/src/EventListener/DataContainerListener.php';

        return $container->services['terminal42_node.listener.data_container'] = new \Terminal42\NodeBundle\EventListener\DataContainerListener(($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)), ($container->services['contao.intl.locales'] ?? self::getContao_Intl_LocalesService($container)), ($container->services['monolog.logger.contao'] ?? $container->load('getMonolog_Logger_ContaoService')), ($container->privates['terminal42_node.permission_checker'] ?? $container->load('getTerminal42Node_PermissionCheckerService')), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['codefog_tags.manager.terminal42_node'] ?? $container->load('getCodefogTags_Manager_Terminal42NodeService')));
    }
}
