<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getThemeHelper_Listener_InsertTagsService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'theme_helper.listener.insert_tags' shared service.
     *
     * @return \Pdir\ThemeHelperBundle\EventListener\InsertTagsListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pdir/contao-theme-helper-bundle/src/EventListener/InsertTagsListener.php';

        return $container->services['theme_helper.listener.insert_tags'] = new \Pdir\ThemeHelperBundle\EventListener\InsertTagsListener(($container->services['contao.framework'] ?? self::getContao_FrameworkService($container)));
    }
}
