<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTerminal42Node_Listener_ContentService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'terminal42_node.listener.content' shared service.
     *
     * @return \Terminal42\NodeBundle\EventListener\ContentListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-node/src/EventListener/ContentListener.php';

        return $container->services['terminal42_node.listener.content'] = new \Terminal42\NodeBundle\EventListener\ContentListener(($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)), ($container->privates['terminal42_node.permission_checker'] ?? $container->load('getTerminal42Node_PermissionCheckerService')));
    }
}
