<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTerminal42Leads_ExportersService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the private 'terminal42_leads.exporters' shared autowired service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['terminal42_leads.exporters'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'csv' => ['privates', 'Terminal42\\LeadsBundle\\Export\\CsvExporter', 'getCsvExporter2Service', true],
            'excel_csv' => ['privates', 'Terminal42\\LeadsBundle\\Export\\PhpSpreadsheetExporter', 'getPhpSpreadsheetExporter2Service', true],
            'html' => ['privates', 'Terminal42\\LeadsBundle\\Export\\PhpSpreadsheetExporter', 'getPhpSpreadsheetExporter2Service', true],
            'ods' => ['privates', 'Terminal42\\LeadsBundle\\Export\\PhpSpreadsheetExporter', 'getPhpSpreadsheetExporter2Service', true],
            'optinCsv' => ['privates', 'Cgoit\\LeadsOptinBundle\\Exporter\\CsvExporter', 'getCsvExporterService', true],
            'optinExcel_csv' => ['privates', 'Cgoit\\LeadsOptinBundle\\Exporter\\PhpSpreadsheetExporter', 'getPhpSpreadsheetExporterService', true],
            'optinHtml' => ['privates', 'Cgoit\\LeadsOptinBundle\\Exporter\\PhpSpreadsheetExporter', 'getPhpSpreadsheetExporterService', true],
            'optinOds' => ['privates', 'Cgoit\\LeadsOptinBundle\\Exporter\\PhpSpreadsheetExporter', 'getPhpSpreadsheetExporterService', true],
            'optinXls' => ['privates', 'Cgoit\\LeadsOptinBundle\\Exporter\\PhpSpreadsheetExporter', 'getPhpSpreadsheetExporterService', true],
            'optinXlsx' => ['privates', 'Cgoit\\LeadsOptinBundle\\Exporter\\PhpSpreadsheetExporter', 'getPhpSpreadsheetExporterService', true],
            'tcpdf' => ['privates', 'Terminal42\\LeadsBundle\\Export\\PhpSpreadsheetExporter', 'getPhpSpreadsheetExporter2Service', true],
            'xls' => ['privates', 'Terminal42\\LeadsBundle\\Export\\PhpSpreadsheetExporter', 'getPhpSpreadsheetExporter2Service', true],
            'xlsx' => ['privates', 'Terminal42\\LeadsBundle\\Export\\PhpSpreadsheetExporter', 'getPhpSpreadsheetExporter2Service', true],
        ], [
            'csv' => 'Terminal42\\LeadsBundle\\Export\\CsvExporter',
            'excel_csv' => 'Terminal42\\LeadsBundle\\Export\\PhpSpreadsheetExporter',
            'html' => 'Terminal42\\LeadsBundle\\Export\\PhpSpreadsheetExporter',
            'ods' => 'Terminal42\\LeadsBundle\\Export\\PhpSpreadsheetExporter',
            'optinCsv' => 'Cgoit\\LeadsOptinBundle\\Exporter\\CsvExporter',
            'optinExcel_csv' => 'Cgoit\\LeadsOptinBundle\\Exporter\\PhpSpreadsheetExporter',
            'optinHtml' => 'Cgoit\\LeadsOptinBundle\\Exporter\\PhpSpreadsheetExporter',
            'optinOds' => 'Cgoit\\LeadsOptinBundle\\Exporter\\PhpSpreadsheetExporter',
            'optinXls' => 'Cgoit\\LeadsOptinBundle\\Exporter\\PhpSpreadsheetExporter',
            'optinXlsx' => 'Cgoit\\LeadsOptinBundle\\Exporter\\PhpSpreadsheetExporter',
            'tcpdf' => 'Terminal42\\LeadsBundle\\Export\\PhpSpreadsheetExporter',
            'xls' => 'Terminal42\\LeadsBundle\\Export\\PhpSpreadsheetExporter',
            'xlsx' => 'Terminal42\\LeadsBundle\\Export\\PhpSpreadsheetExporter',
        ]);
    }
}
