<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserPermissionsListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Terminal42\LeadsBundle\EventListener\DataContainer\UserPermissionsListener' shared autowired service.
     *
     * @return \Terminal42\LeadsBundle\EventListener\DataContainer\UserPermissionsListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-leads/src/EventListener/DataContainer/UserPermissionsListener.php';

        return $container->services['Terminal42\\LeadsBundle\\EventListener\\DataContainer\\UserPermissionsListener'] = new \Terminal42\LeadsBundle\EventListener\DataContainer\UserPermissionsListener(($container->services['security.authorization_checker'] ?? self::getSecurity_AuthorizationCheckerService($container)));
    }
}
