<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserNavigationListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Terminal42\LeadsBundle\EventListener\UserNavigationListener' shared autowired service.
     *
     * @return \Terminal42\LeadsBundle\EventListener\UserNavigationListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-leads/src/EventListener/UserNavigationListener.php';

        return $container->services['Terminal42\\LeadsBundle\\EventListener\\UserNavigationListener'] = new \Terminal42\LeadsBundle\EventListener\UserNavigationListener(($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['contao.routing.scope_matcher'] ?? self::getContao_Routing_ScopeMatcherService($container)), ($container->services['security.authorization_checker'] ?? self::getSecurity_AuthorizationCheckerService($container)), ($container->services['router'] ?? self::getRouterService($container)), ($container->services['translator'] ?? self::getTranslatorService($container)), ($container->services['assets.packages'] ?? self::getAssets_PackagesService($container)));
    }
}
