<?php

namespace ContainerXiLrMqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVisitorsFeAjaxControllerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'BugBuster\VisitorsBundle\Controller\VisitorsFeAjaxController' shared autowired service.
     *
     * @return \BugBuster\VisitorsBundle\Controller\VisitorsFeAjaxController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/bugbuster/contao-visitors-bundle/src/Controller/VisitorsFeAjaxController.php';

        return $container->services['BugBuster\\VisitorsBundle\\Controller\\VisitorsFeAjaxController'] = new \BugBuster\VisitorsBundle\Controller\VisitorsFeAjaxController(($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)), ($container->services['BugBuster\\VisitorsBundle\\Classes\\VisitorLogger'] ?? $container->load('getVisitorLoggerService')), ($container->services['BugBuster\\VisitorsBundle\\Classes\\VisitorCalculator'] ?? $container->load('getVisitorCalculatorService')));
    }
}
