<?php

namespace Proxies\__CG__\Contao\CoreBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CrawlQueue extends \Contao\CoreBundle\Entity\CrawlQueue implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        'foundOn' => [parent::class, 'foundOn', null],
        'id' => [parent::class, 'id', null],
        'jobId' => [parent::class, 'jobId', null],
        'level' => [parent::class, 'level', null],
        'processed' => [parent::class, 'processed', null],
        'tags' => [parent::class, 'tags', null],
        'uri' => [parent::class, 'uri', null],
        'uriHash' => [parent::class, 'uriHash', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
