<?php

namespace Proxies\__CG__\Contao\CoreBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TrustedDevice extends \Contao\CoreBundle\Entity\TrustedDevice implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'created' => [parent::class, 'created', null],
        "\0".'*'."\0".'deviceFamily' => [parent::class, 'deviceFamily', null],
        "\0".'*'."\0".'id' => [parent::class, 'id', null],
        "\0".'*'."\0".'osFamily' => [parent::class, 'osFamily', null],
        "\0".'*'."\0".'uaFamily' => [parent::class, 'uaFamily', null],
        "\0".'*'."\0".'userAgent' => [parent::class, 'userAgent', null],
        "\0".'*'."\0".'userClass' => [parent::class, 'userClass', null],
        "\0".'*'."\0".'userId' => [parent::class, 'userId', null],
        'created' => [parent::class, 'created', null],
        'deviceFamily' => [parent::class, 'deviceFamily', null],
        'id' => [parent::class, 'id', null],
        'osFamily' => [parent::class, 'osFamily', null],
        'uaFamily' => [parent::class, 'uaFamily', null],
        'userAgent' => [parent::class, 'userAgent', null],
        'userClass' => [parent::class, 'userClass', null],
        'userId' => [parent::class, 'userId', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
